/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExpenseNoteRowDetails implements java.io.Serializable {

	private static final long serialVersionUID = 853387353;

	private java.math.BigInteger   expenseNoteRowDetailId;
	private java.math.BigInteger   expenseNoteId;
	private org.joda.time.DateTime revision;
	private java.math.BigInteger   typeId;
	private java.math.BigDecimal   total;
	private org.joda.time.DateTime date;
	private java.lang.String       operatorId;
	private java.lang.String       domainId;
	private java.lang.String       paymentCompany;
	private java.lang.String       invoice;
	private java.lang.String       invoiceNumber;
	private java.lang.String       present;
	private java.lang.String       customerId;
	private java.lang.String       pointOfSale;
	private java.math.BigDecimal   km;
	private java.math.BigDecimal   totalDoc;
	private java.lang.String       consumptive;
	private java.lang.String       currency;
	private java.lang.String       change;
	private java.lang.String       currencyCostDoc;
	private java.lang.String       description;

	public ExpenseNoteRowDetails() {}

	public ExpenseNoteRowDetails(
		java.math.BigInteger   expenseNoteRowDetailId,
		java.math.BigInteger   expenseNoteId,
		org.joda.time.DateTime revision,
		java.math.BigInteger   typeId,
		java.math.BigDecimal   total,
		org.joda.time.DateTime date,
		java.lang.String       operatorId,
		java.lang.String       domainId,
		java.lang.String       paymentCompany,
		java.lang.String       invoice,
		java.lang.String       invoiceNumber,
		java.lang.String       present,
		java.lang.String       customerId,
		java.lang.String       pointOfSale,
		java.math.BigDecimal   km,
		java.math.BigDecimal   totalDoc,
		java.lang.String       consumptive,
		java.lang.String       currency,
		java.lang.String       change,
		java.lang.String       currencyCostDoc,
		java.lang.String       description
	) {
		this.expenseNoteRowDetailId = expenseNoteRowDetailId;
		this.expenseNoteId = expenseNoteId;
		this.revision = revision;
		this.typeId = typeId;
		this.total = total;
		this.date = date;
		this.operatorId = operatorId;
		this.domainId = domainId;
		this.paymentCompany = paymentCompany;
		this.invoice = invoice;
		this.invoiceNumber = invoiceNumber;
		this.present = present;
		this.customerId = customerId;
		this.pointOfSale = pointOfSale;
		this.km = km;
		this.totalDoc = totalDoc;
		this.consumptive = consumptive;
		this.currency = currency;
		this.change = change;
		this.currencyCostDoc = currencyCostDoc;
		this.description = description;
	}

	public java.math.BigInteger getExpenseNoteRowDetailId() {
		return this.expenseNoteRowDetailId;
	}

	public void setExpenseNoteRowDetailId(java.math.BigInteger expenseNoteRowDetailId) {
		this.expenseNoteRowDetailId = expenseNoteRowDetailId;
	}

	public java.math.BigInteger getExpenseNoteId() {
		return this.expenseNoteId;
	}

	public void setExpenseNoteId(java.math.BigInteger expenseNoteId) {
		this.expenseNoteId = expenseNoteId;
	}

	public org.joda.time.DateTime getRevision() {
		return this.revision;
	}

	public void setRevision(org.joda.time.DateTime revision) {
		this.revision = revision;
	}

	public java.math.BigInteger getTypeId() {
		return this.typeId;
	}

	public void setTypeId(java.math.BigInteger typeId) {
		this.typeId = typeId;
	}

	public java.math.BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(java.math.BigDecimal total) {
		this.total = total;
	}

	public org.joda.time.DateTime getDate() {
		return this.date;
	}

	public void setDate(org.joda.time.DateTime date) {
		this.date = date;
	}

	public java.lang.String getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(java.lang.String operatorId) {
		this.operatorId = operatorId;
	}

	public java.lang.String getDomainId() {
		return this.domainId;
	}

	public void setDomainId(java.lang.String domainId) {
		this.domainId = domainId;
	}

	public java.lang.String getPaymentCompany() {
		return this.paymentCompany;
	}

	public void setPaymentCompany(java.lang.String paymentCompany) {
		this.paymentCompany = paymentCompany;
	}

	public java.lang.String getInvoice() {
		return this.invoice;
	}

	public void setInvoice(java.lang.String invoice) {
		this.invoice = invoice;
	}

	public java.lang.String getInvoiceNumber() {
		return this.invoiceNumber;
	}

	public void setInvoiceNumber(java.lang.String invoiceNumber) {
		this.invoiceNumber = invoiceNumber;
	}

	public java.lang.String getPresent() {
		return this.present;
	}

	public void setPresent(java.lang.String present) {
		this.present = present;
	}

	public java.lang.String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(java.lang.String customerId) {
		this.customerId = customerId;
	}

	public java.lang.String getPointOfSale() {
		return this.pointOfSale;
	}

	public void setPointOfSale(java.lang.String pointOfSale) {
		this.pointOfSale = pointOfSale;
	}

	public java.math.BigDecimal getKm() {
		return this.km;
	}

	public void setKm(java.math.BigDecimal km) {
		this.km = km;
	}

	public java.math.BigDecimal getTotalDoc() {
		return this.totalDoc;
	}

	public void setTotalDoc(java.math.BigDecimal totalDoc) {
		this.totalDoc = totalDoc;
	}

	public java.lang.String getConsumptive() {
		return this.consumptive;
	}

	public void setConsumptive(java.lang.String consumptive) {
		this.consumptive = consumptive;
	}

	public java.lang.String getCurrency() {
		return this.currency;
	}

	public void setCurrency(java.lang.String currency) {
		this.currency = currency;
	}

	public java.lang.String getChange() {
		return this.change;
	}

	public void setChange(java.lang.String change) {
		this.change = change;
	}

	public java.lang.String getCurrencyCostDoc() {
		return this.currencyCostDoc;
	}

	public void setCurrencyCostDoc(java.lang.String currencyCostDoc) {
		this.currencyCostDoc = currencyCostDoc;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}
}
