/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExpenseNoteDocumentLinks implements java.io.Serializable {

	private static final long serialVersionUID = -773018723;

	private java.math.BigInteger expenseNoteId;
	private java.math.BigInteger expenseNoteDocumentId;
	private java.lang.String     operatorId;
	private java.lang.String     domainId;

	public ExpenseNoteDocumentLinks() {}

	public ExpenseNoteDocumentLinks(
		java.math.BigInteger expenseNoteId,
		java.math.BigInteger expenseNoteDocumentId,
		java.lang.String     operatorId,
		java.lang.String     domainId
	) {
		this.expenseNoteId = expenseNoteId;
		this.expenseNoteDocumentId = expenseNoteDocumentId;
		this.operatorId = operatorId;
		this.domainId = domainId;
	}

	public java.math.BigInteger getExpenseNoteId() {
		return this.expenseNoteId;
	}

	public void setExpenseNoteId(java.math.BigInteger expenseNoteId) {
		this.expenseNoteId = expenseNoteId;
	}

	public java.math.BigInteger getExpenseNoteDocumentId() {
		return this.expenseNoteDocumentId;
	}

	public void setExpenseNoteDocumentId(java.math.BigInteger expenseNoteDocumentId) {
		this.expenseNoteDocumentId = expenseNoteDocumentId;
	}

	public java.lang.String getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(java.lang.String operatorId) {
		this.operatorId = operatorId;
	}

	public java.lang.String getDomainId() {
		return this.domainId;
	}

	public void setDomainId(java.lang.String domainId) {
		this.domainId = domainId;
	}
}
