/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExpenseNoteDocuments implements java.io.Serializable {

	private static final long serialVersionUID = -1768792151;

	private java.math.BigInteger   expenseNoteDocumentId;
	private java.lang.Long         file;
	private java.lang.String       filename;
	private java.math.BigInteger   expenseNoteId;
	private org.joda.time.DateTime revision;
	private java.lang.String       operatorIdLockFile;

	public ExpenseNoteDocuments() {}

	public ExpenseNoteDocuments(
		java.math.BigInteger   expenseNoteDocumentId,
		java.lang.Long         file,
		java.lang.String       filename,
		java.math.BigInteger   expenseNoteId,
		org.joda.time.DateTime revision,
		java.lang.String       operatorIdLockFile
	) {
		this.expenseNoteDocumentId = expenseNoteDocumentId;
		this.file = file;
		this.filename = filename;
		this.expenseNoteId = expenseNoteId;
		this.revision = revision;
		this.operatorIdLockFile = operatorIdLockFile;
	}

	public java.math.BigInteger getExpenseNoteDocumentId() {
		return this.expenseNoteDocumentId;
	}

	public void setExpenseNoteDocumentId(java.math.BigInteger expenseNoteDocumentId) {
		this.expenseNoteDocumentId = expenseNoteDocumentId;
	}

	public java.lang.Long getFile() {
		return this.file;
	}

	public void setFile(java.lang.Long file) {
		this.file = file;
	}

	public java.lang.String getFilename() {
		return this.filename;
	}

	public void setFilename(java.lang.String filename) {
		this.filename = filename;
	}

	public java.math.BigInteger getExpenseNoteId() {
		return this.expenseNoteId;
	}

	public void setExpenseNoteId(java.math.BigInteger expenseNoteId) {
		this.expenseNoteId = expenseNoteId;
	}

	public org.joda.time.DateTime getRevision() {
		return this.revision;
	}

	public void setRevision(org.joda.time.DateTime revision) {
		this.revision = revision;
	}

	public java.lang.String getOperatorIdLockFile() {
		return this.operatorIdLockFile;
	}

	public void setOperatorIdLockFile(java.lang.String operatorIdLockFile) {
		this.operatorIdLockFile = operatorIdLockFile;
	}
}
