/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExpenseNoteRows implements java.io.Serializable {

	private static final long serialVersionUID = 1725489712;

	private java.math.BigInteger   expenseNoteRowId;
	private java.math.BigInteger   expenseNoteId;
	private org.joda.time.DateTime revision;
	private java.lang.String       description;
	private java.math.BigDecimal   km;
	private java.math.BigDecimal   stay;
	private java.math.BigDecimal   highway;
	private java.math.BigDecimal   park;
	private java.math.BigDecimal   meals;
	private java.math.BigDecimal   amountKm;
	private java.math.BigDecimal   other;
	private java.math.BigDecimal   total;
	private org.joda.time.DateTime date;
	private java.lang.String       operatorId;
	private java.lang.String       domainId;
	private java.lang.String       customerId;
	private java.lang.String       paymentCompany;
	private java.lang.String       invoice;
	private java.lang.String       invoiceNumber;
	private java.lang.String       pointOfSale;

	public ExpenseNoteRows() {}

	public ExpenseNoteRows(
		java.math.BigInteger   expenseNoteRowId,
		java.math.BigInteger   expenseNoteId,
		org.joda.time.DateTime revision,
		java.lang.String       description,
		java.math.BigDecimal   km,
		java.math.BigDecimal   stay,
		java.math.BigDecimal   highway,
		java.math.BigDecimal   park,
		java.math.BigDecimal   meals,
		java.math.BigDecimal   amountKm,
		java.math.BigDecimal   other,
		java.math.BigDecimal   total,
		org.joda.time.DateTime date,
		java.lang.String       operatorId,
		java.lang.String       domainId,
		java.lang.String       customerId,
		java.lang.String       paymentCompany,
		java.lang.String       invoice,
		java.lang.String       invoiceNumber,
		java.lang.String       pointOfSale
	) {
		this.expenseNoteRowId = expenseNoteRowId;
		this.expenseNoteId = expenseNoteId;
		this.revision = revision;
		this.description = description;
		this.km = km;
		this.stay = stay;
		this.highway = highway;
		this.park = park;
		this.meals = meals;
		this.amountKm = amountKm;
		this.other = other;
		this.total = total;
		this.date = date;
		this.operatorId = operatorId;
		this.domainId = domainId;
		this.customerId = customerId;
		this.paymentCompany = paymentCompany;
		this.invoice = invoice;
		this.invoiceNumber = invoiceNumber;
		this.pointOfSale = pointOfSale;
	}

	public java.math.BigInteger getExpenseNoteRowId() {
		return this.expenseNoteRowId;
	}

	public void setExpenseNoteRowId(java.math.BigInteger expenseNoteRowId) {
		this.expenseNoteRowId = expenseNoteRowId;
	}

	public java.math.BigInteger getExpenseNoteId() {
		return this.expenseNoteId;
	}

	public void setExpenseNoteId(java.math.BigInteger expenseNoteId) {
		this.expenseNoteId = expenseNoteId;
	}

	public org.joda.time.DateTime getRevision() {
		return this.revision;
	}

	public void setRevision(org.joda.time.DateTime revision) {
		this.revision = revision;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.math.BigDecimal getKm() {
		return this.km;
	}

	public void setKm(java.math.BigDecimal km) {
		this.km = km;
	}

	public java.math.BigDecimal getStay() {
		return this.stay;
	}

	public void setStay(java.math.BigDecimal stay) {
		this.stay = stay;
	}

	public java.math.BigDecimal getHighway() {
		return this.highway;
	}

	public void setHighway(java.math.BigDecimal highway) {
		this.highway = highway;
	}

	public java.math.BigDecimal getPark() {
		return this.park;
	}

	public void setPark(java.math.BigDecimal park) {
		this.park = park;
	}

	public java.math.BigDecimal getMeals() {
		return this.meals;
	}

	public void setMeals(java.math.BigDecimal meals) {
		this.meals = meals;
	}

	public java.math.BigDecimal getAmountKm() {
		return this.amountKm;
	}

	public void setAmountKm(java.math.BigDecimal amountKm) {
		this.amountKm = amountKm;
	}

	public java.math.BigDecimal getOther() {
		return this.other;
	}

	public void setOther(java.math.BigDecimal other) {
		this.other = other;
	}

	public java.math.BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(java.math.BigDecimal total) {
		this.total = total;
	}

	public org.joda.time.DateTime getDate() {
		return this.date;
	}

	public void setDate(org.joda.time.DateTime date) {
		this.date = date;
	}

	public java.lang.String getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(java.lang.String operatorId) {
		this.operatorId = operatorId;
	}

	public java.lang.String getDomainId() {
		return this.domainId;
	}

	public void setDomainId(java.lang.String domainId) {
		this.domainId = domainId;
	}

	public java.lang.String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(java.lang.String customerId) {
		this.customerId = customerId;
	}

	public java.lang.String getPaymentCompany() {
		return this.paymentCompany;
	}

	public void setPaymentCompany(java.lang.String paymentCompany) {
		this.paymentCompany = paymentCompany;
	}

	public java.lang.String getInvoice() {
		return this.invoice;
	}

	public void setInvoice(java.lang.String invoice) {
		this.invoice = invoice;
	}

	public java.lang.String getInvoiceNumber() {
		return this.invoiceNumber;
	}

	public void setInvoiceNumber(java.lang.String invoiceNumber) {
		this.invoiceNumber = invoiceNumber;
	}

	public java.lang.String getPointOfSale() {
		return this.pointOfSale;
	}

	public void setPointOfSale(java.lang.String pointOfSale) {
		this.pointOfSale = pointOfSale;
	}
}
