/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExpenseNoteRowDocuments implements java.io.Serializable {

	private static final long serialVersionUID = -2024799405;

	private java.math.BigInteger   expenseNoteRowDocumentId;
	private java.math.BigInteger   expenseNoteRowDetailId;
	private org.joda.time.DateTime revision;
	private java.lang.Long         file;
	private java.lang.String       filename;
	private java.math.BigInteger   expenseNoteId;
	private java.lang.String       operatorId;
	private java.lang.String       domainId;
	private java.lang.String       operatorIdLockFile;

	public ExpenseNoteRowDocuments() {}

	public ExpenseNoteRowDocuments(
		java.math.BigInteger   expenseNoteRowDocumentId,
		java.math.BigInteger   expenseNoteRowDetailId,
		org.joda.time.DateTime revision,
		java.lang.Long         file,
		java.lang.String       filename,
		java.math.BigInteger   expenseNoteId,
		java.lang.String       operatorId,
		java.lang.String       domainId,
		java.lang.String       operatorIdLockFile
	) {
		this.expenseNoteRowDocumentId = expenseNoteRowDocumentId;
		this.expenseNoteRowDetailId = expenseNoteRowDetailId;
		this.revision = revision;
		this.file = file;
		this.filename = filename;
		this.expenseNoteId = expenseNoteId;
		this.operatorId = operatorId;
		this.domainId = domainId;
		this.operatorIdLockFile = operatorIdLockFile;
	}

	public java.math.BigInteger getExpenseNoteRowDocumentId() {
		return this.expenseNoteRowDocumentId;
	}

	public void setExpenseNoteRowDocumentId(java.math.BigInteger expenseNoteRowDocumentId) {
		this.expenseNoteRowDocumentId = expenseNoteRowDocumentId;
	}

	public java.math.BigInteger getExpenseNoteRowDetailId() {
		return this.expenseNoteRowDetailId;
	}

	public void setExpenseNoteRowDetailId(java.math.BigInteger expenseNoteRowDetailId) {
		this.expenseNoteRowDetailId = expenseNoteRowDetailId;
	}

	public org.joda.time.DateTime getRevision() {
		return this.revision;
	}

	public void setRevision(org.joda.time.DateTime revision) {
		this.revision = revision;
	}

	public java.lang.Long getFile() {
		return this.file;
	}

	public void setFile(java.lang.Long file) {
		this.file = file;
	}

	public java.lang.String getFilename() {
		return this.filename;
	}

	public void setFilename(java.lang.String filename) {
		this.filename = filename;
	}

	public java.math.BigInteger getExpenseNoteId() {
		return this.expenseNoteId;
	}

	public void setExpenseNoteId(java.math.BigInteger expenseNoteId) {
		this.expenseNoteId = expenseNoteId;
	}

	public java.lang.String getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(java.lang.String operatorId) {
		this.operatorId = operatorId;
	}

	public java.lang.String getDomainId() {
		return this.domainId;
	}

	public void setDomainId(java.lang.String domainId) {
		this.domainId = domainId;
	}

	public java.lang.String getOperatorIdLockFile() {
		return this.operatorIdLockFile;
	}

	public void setOperatorIdLockFile(java.lang.String operatorIdLockFile) {
		this.operatorIdLockFile = operatorIdLockFile;
	}
}
