/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FoldersGroups implements java.io.Serializable {

	private static final long serialVersionUID = -1771651678;

	private java.lang.Integer associationId;
	private java.lang.String  folderId;
	private java.lang.String  groupId;

	public FoldersGroups() {}

	public FoldersGroups(
		java.lang.Integer associationId,
		java.lang.String  folderId,
		java.lang.String  groupId
	) {
		this.associationId = associationId;
		this.folderId = folderId;
		this.groupId = groupId;
	}

	public java.lang.Integer getAssociationId() {
		return this.associationId;
	}

	public void setAssociationId(java.lang.Integer associationId) {
		this.associationId = associationId;
	}

	public java.lang.String getFolderId() {
		return this.folderId;
	}

	public void setFolderId(java.lang.String folderId) {
		this.folderId = folderId;
	}

	public java.lang.String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(java.lang.String groupId) {
		this.groupId = groupId;
	}
}
