/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Folders implements java.io.Serializable {

	private static final long serialVersionUID = 1336272596;

	private java.lang.String  folderId;
	private java.lang.String  name;
	private java.lang.String  description;
	private java.lang.Boolean expired;

	public Folders() {}

	public Folders(
		java.lang.String  folderId,
		java.lang.String  name,
		java.lang.String  description,
		java.lang.Boolean expired
	) {
		this.folderId = folderId;
		this.name = name;
		this.description = description;
		this.expired = expired;
	}

	public java.lang.String getFolderId() {
		return this.folderId;
	}

	public void setFolderId(java.lang.String folderId) {
		this.folderId = folderId;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.Boolean getExpired() {
		return this.expired;
	}

	public void setExpired(java.lang.Boolean expired) {
		this.expired = expired;
	}
}
