/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupsUsers implements java.io.Serializable {

	private static final long serialVersionUID = -1102143605;

	private java.lang.Integer associationId;
	private java.lang.String  groupId;
	private java.lang.String  userId;

	public GroupsUsers() {}

	public GroupsUsers(
		java.lang.Integer associationId,
		java.lang.String  groupId,
		java.lang.String  userId
	) {
		this.associationId = associationId;
		this.groupId = groupId;
		this.userId = userId;
	}

	public java.lang.Integer getAssociationId() {
		return this.associationId;
	}

	public void setAssociationId(java.lang.Integer associationId) {
		this.associationId = associationId;
	}

	public java.lang.String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(java.lang.String groupId) {
		this.groupId = groupId;
	}

	public java.lang.String getUserId() {
		return this.userId;
	}

	public void setUserId(java.lang.String userId) {
		this.userId = userId;
	}
}
