/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LineManagerUsers implements java.io.Serializable {

	private static final long serialVersionUID = -1626162922;

	private java.lang.String domainId;
	private java.lang.String lineManagerUserId;
	private java.lang.String userId;

	public LineManagerUsers() {}

	public LineManagerUsers(
		java.lang.String domainId,
		java.lang.String lineManagerUserId,
		java.lang.String userId
	) {
		this.domainId = domainId;
		this.lineManagerUserId = lineManagerUserId;
		this.userId = userId;
	}

	public java.lang.String getDomainId() {
		return this.domainId;
	}

	public void setDomainId(java.lang.String domainId) {
		this.domainId = domainId;
	}

	public java.lang.String getLineManagerUserId() {
		return this.lineManagerUserId;
	}

	public void setLineManagerUserId(java.lang.String lineManagerUserId) {
		this.lineManagerUserId = lineManagerUserId;
	}

	public java.lang.String getUserId() {
		return this.userId;
	}

	public void setUserId(java.lang.String userId) {
		this.userId = userId;
	}
}
