/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LineHours implements java.io.Serializable {

	private static final long serialVersionUID = -2012020220;

	private java.lang.Integer id;
	private java.lang.String  domainId;
	private java.lang.Integer hourProfileId;
	private java.lang.Integer lineId;
	private java.lang.String  _1E;
	private java.lang.String  _1U;
	private java.lang.String  _1H;
	private java.lang.String  _2E;
	private java.lang.String  _2U;
	private java.lang.String  _2H;
	private java.lang.String  _3E;
	private java.lang.String  _3U;
	private java.lang.String  _3H;
	private java.lang.String  _4E;
	private java.lang.String  _4U;
	private java.lang.String  _4H;
	private java.lang.String  _5E;
	private java.lang.String  _5U;
	private java.lang.String  _5H;
	private java.lang.String  _6E;
	private java.lang.String  _6U;
	private java.lang.String  _6H;
	private java.lang.String  _7E;
	private java.lang.String  _7U;
	private java.lang.String  _7H;

	public LineHours() {}

	public LineHours(
		java.lang.Integer id,
		java.lang.String  domainId,
		java.lang.Integer hourProfileId,
		java.lang.Integer lineId,
		java.lang.String  _1E,
		java.lang.String  _1U,
		java.lang.String  _1H,
		java.lang.String  _2E,
		java.lang.String  _2U,
		java.lang.String  _2H,
		java.lang.String  _3E,
		java.lang.String  _3U,
		java.lang.String  _3H,
		java.lang.String  _4E,
		java.lang.String  _4U,
		java.lang.String  _4H,
		java.lang.String  _5E,
		java.lang.String  _5U,
		java.lang.String  _5H,
		java.lang.String  _6E,
		java.lang.String  _6U,
		java.lang.String  _6H,
		java.lang.String  _7E,
		java.lang.String  _7U,
		java.lang.String  _7H
	) {
		this.id = id;
		this.domainId = domainId;
		this.hourProfileId = hourProfileId;
		this.lineId = lineId;
		this._1E = _1E;
		this._1U = _1U;
		this._1H = _1H;
		this._2E = _2E;
		this._2U = _2U;
		this._2H = _2H;
		this._3E = _3E;
		this._3U = _3U;
		this._3H = _3H;
		this._4E = _4E;
		this._4U = _4U;
		this._4H = _4H;
		this._5E = _5E;
		this._5U = _5U;
		this._5H = _5H;
		this._6E = _6E;
		this._6U = _6U;
		this._6H = _6H;
		this._7E = _7E;
		this._7U = _7U;
		this._7H = _7H;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getDomainId() {
		return this.domainId;
	}

	public void setDomainId(java.lang.String domainId) {
		this.domainId = domainId;
	}

	public java.lang.Integer getHourProfileId() {
		return this.hourProfileId;
	}

	public void setHourProfileId(java.lang.Integer hourProfileId) {
		this.hourProfileId = hourProfileId;
	}

	public java.lang.Integer getLineId() {
		return this.lineId;
	}

	public void setLineId(java.lang.Integer lineId) {
		this.lineId = lineId;
	}

	public java.lang.String get_1E() {
		return this._1E;
	}

	public void set_1E(java.lang.String _1E) {
		this._1E = _1E;
	}

	public java.lang.String get_1U() {
		return this._1U;
	}

	public void set_1U(java.lang.String _1U) {
		this._1U = _1U;
	}

	public java.lang.String get_1H() {
		return this._1H;
	}

	public void set_1H(java.lang.String _1H) {
		this._1H = _1H;
	}

	public java.lang.String get_2E() {
		return this._2E;
	}

	public void set_2E(java.lang.String _2E) {
		this._2E = _2E;
	}

	public java.lang.String get_2U() {
		return this._2U;
	}

	public void set_2U(java.lang.String _2U) {
		this._2U = _2U;
	}

	public java.lang.String get_2H() {
		return this._2H;
	}

	public void set_2H(java.lang.String _2H) {
		this._2H = _2H;
	}

	public java.lang.String get_3E() {
		return this._3E;
	}

	public void set_3E(java.lang.String _3E) {
		this._3E = _3E;
	}

	public java.lang.String get_3U() {
		return this._3U;
	}

	public void set_3U(java.lang.String _3U) {
		this._3U = _3U;
	}

	public java.lang.String get_3H() {
		return this._3H;
	}

	public void set_3H(java.lang.String _3H) {
		this._3H = _3H;
	}

	public java.lang.String get_4E() {
		return this._4E;
	}

	public void set_4E(java.lang.String _4E) {
		this._4E = _4E;
	}

	public java.lang.String get_4U() {
		return this._4U;
	}

	public void set_4U(java.lang.String _4U) {
		this._4U = _4U;
	}

	public java.lang.String get_4H() {
		return this._4H;
	}

	public void set_4H(java.lang.String _4H) {
		this._4H = _4H;
	}

	public java.lang.String get_5E() {
		return this._5E;
	}

	public void set_5E(java.lang.String _5E) {
		this._5E = _5E;
	}

	public java.lang.String get_5U() {
		return this._5U;
	}

	public void set_5U(java.lang.String _5U) {
		this._5U = _5U;
	}

	public java.lang.String get_5H() {
		return this._5H;
	}

	public void set_5H(java.lang.String _5H) {
		this._5H = _5H;
	}

	public java.lang.String get_6E() {
		return this._6E;
	}

	public void set_6E(java.lang.String _6E) {
		this._6E = _6E;
	}

	public java.lang.String get_6U() {
		return this._6U;
	}

	public void set_6U(java.lang.String _6U) {
		this._6U = _6U;
	}

	public java.lang.String get_6H() {
		return this._6H;
	}

	public void set_6H(java.lang.String _6H) {
		this._6H = _6H;
	}

	public java.lang.String get_7E() {
		return this._7E;
	}

	public void set_7E(java.lang.String _7E) {
		this._7E = _7E;
	}

	public java.lang.String get_7U() {
		return this._7U;
	}

	public void set_7U(java.lang.String _7U) {
		this._7U = _7U;
	}

	public java.lang.String get_7H() {
		return this._7H;
	}

	public void set_7H(java.lang.String _7H) {
		this._7H = _7H;
	}
}
