/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TimetableAttendancesheet implements java.io.Serializable {

	private static final long serialVersionUID = -1179765770;

	private java.lang.String     operatorId;
	private java.lang.Short      groupId;
	private java.lang.String     day;
	private java.math.BigDecimal hWork;
	private java.math.BigDecimal hPermits;
	private java.math.BigDecimal hExtra_1;
	private java.math.BigDecimal hExtra_2;
	private java.math.BigDecimal hExtra_3;
	private java.math.BigDecimal hHolidays;
	private java.math.BigDecimal hDisease;
	private java.math.BigDecimal hTotal;
	private java.lang.Short      noLoad;
	private java.math.BigDecimal hReports;
	private java.math.BigDecimal hWorkTot;
	private java.math.BigDecimal hWorkH;
	private java.math.BigDecimal hWorkMin;
	private java.math.BigDecimal hPermitsTot;
	private java.math.BigDecimal hPermitsH;
	private java.math.BigDecimal hPermitsMin;
	private java.math.BigDecimal hExtra_1Tot;
	private java.math.BigDecimal hExtra_2Tot;
	private java.math.BigDecimal hExtra_2H;
	private java.math.BigDecimal hExtra_2Min;
	private java.math.BigDecimal hExtra_3Tot;
	private java.math.BigDecimal hExtra_3H;
	private java.math.BigDecimal hExtra_3Min;
	private java.math.BigDecimal hHolidaysTot;
	private java.math.BigDecimal hHolidaysH;
	private java.math.BigDecimal hHolidaysMin;
	private java.math.BigDecimal hDiseaseTot;
	private java.math.BigDecimal hDiseaseH;
	private java.math.BigDecimal hDiseaseMin;
	private java.math.BigDecimal hTotalTot;
	private java.math.BigDecimal hTotalH;
	private java.math.BigDecimal hTotalMin;
	private java.math.BigDecimal hReportsTot;
	private java.math.BigDecimal hReportsH;
	private java.math.BigDecimal hReportsMin;
	private java.lang.String     username;

	public TimetableAttendancesheet() {}

	public TimetableAttendancesheet(
		java.lang.String     operatorId,
		java.lang.Short      groupId,
		java.lang.String     day,
		java.math.BigDecimal hWork,
		java.math.BigDecimal hPermits,
		java.math.BigDecimal hExtra_1,
		java.math.BigDecimal hExtra_2,
		java.math.BigDecimal hExtra_3,
		java.math.BigDecimal hHolidays,
		java.math.BigDecimal hDisease,
		java.math.BigDecimal hTotal,
		java.lang.Short      noLoad,
		java.math.BigDecimal hReports,
		java.math.BigDecimal hWorkTot,
		java.math.BigDecimal hWorkH,
		java.math.BigDecimal hWorkMin,
		java.math.BigDecimal hPermitsTot,
		java.math.BigDecimal hPermitsH,
		java.math.BigDecimal hPermitsMin,
		java.math.BigDecimal hExtra_1Tot,
		java.math.BigDecimal hExtra_2Tot,
		java.math.BigDecimal hExtra_2H,
		java.math.BigDecimal hExtra_2Min,
		java.math.BigDecimal hExtra_3Tot,
		java.math.BigDecimal hExtra_3H,
		java.math.BigDecimal hExtra_3Min,
		java.math.BigDecimal hHolidaysTot,
		java.math.BigDecimal hHolidaysH,
		java.math.BigDecimal hHolidaysMin,
		java.math.BigDecimal hDiseaseTot,
		java.math.BigDecimal hDiseaseH,
		java.math.BigDecimal hDiseaseMin,
		java.math.BigDecimal hTotalTot,
		java.math.BigDecimal hTotalH,
		java.math.BigDecimal hTotalMin,
		java.math.BigDecimal hReportsTot,
		java.math.BigDecimal hReportsH,
		java.math.BigDecimal hReportsMin,
		java.lang.String     username
	) {
		this.operatorId = operatorId;
		this.groupId = groupId;
		this.day = day;
		this.hWork = hWork;
		this.hPermits = hPermits;
		this.hExtra_1 = hExtra_1;
		this.hExtra_2 = hExtra_2;
		this.hExtra_3 = hExtra_3;
		this.hHolidays = hHolidays;
		this.hDisease = hDisease;
		this.hTotal = hTotal;
		this.noLoad = noLoad;
		this.hReports = hReports;
		this.hWorkTot = hWorkTot;
		this.hWorkH = hWorkH;
		this.hWorkMin = hWorkMin;
		this.hPermitsTot = hPermitsTot;
		this.hPermitsH = hPermitsH;
		this.hPermitsMin = hPermitsMin;
		this.hExtra_1Tot = hExtra_1Tot;
		this.hExtra_2Tot = hExtra_2Tot;
		this.hExtra_2H = hExtra_2H;
		this.hExtra_2Min = hExtra_2Min;
		this.hExtra_3Tot = hExtra_3Tot;
		this.hExtra_3H = hExtra_3H;
		this.hExtra_3Min = hExtra_3Min;
		this.hHolidaysTot = hHolidaysTot;
		this.hHolidaysH = hHolidaysH;
		this.hHolidaysMin = hHolidaysMin;
		this.hDiseaseTot = hDiseaseTot;
		this.hDiseaseH = hDiseaseH;
		this.hDiseaseMin = hDiseaseMin;
		this.hTotalTot = hTotalTot;
		this.hTotalH = hTotalH;
		this.hTotalMin = hTotalMin;
		this.hReportsTot = hReportsTot;
		this.hReportsH = hReportsH;
		this.hReportsMin = hReportsMin;
		this.username = username;
	}

	public java.lang.String getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(java.lang.String operatorId) {
		this.operatorId = operatorId;
	}

	public java.lang.Short getGroupId() {
		return this.groupId;
	}

	public void setGroupId(java.lang.Short groupId) {
		this.groupId = groupId;
	}

	public java.lang.String getDay() {
		return this.day;
	}

	public void setDay(java.lang.String day) {
		this.day = day;
	}

	public java.math.BigDecimal getHWork() {
		return this.hWork;
	}

	public void setHWork(java.math.BigDecimal hWork) {
		this.hWork = hWork;
	}

	public java.math.BigDecimal getHPermits() {
		return this.hPermits;
	}

	public void setHPermits(java.math.BigDecimal hPermits) {
		this.hPermits = hPermits;
	}

	public java.math.BigDecimal getHExtra_1() {
		return this.hExtra_1;
	}

	public void setHExtra_1(java.math.BigDecimal hExtra_1) {
		this.hExtra_1 = hExtra_1;
	}

	public java.math.BigDecimal getHExtra_2() {
		return this.hExtra_2;
	}

	public void setHExtra_2(java.math.BigDecimal hExtra_2) {
		this.hExtra_2 = hExtra_2;
	}

	public java.math.BigDecimal getHExtra_3() {
		return this.hExtra_3;
	}

	public void setHExtra_3(java.math.BigDecimal hExtra_3) {
		this.hExtra_3 = hExtra_3;
	}

	public java.math.BigDecimal getHHolidays() {
		return this.hHolidays;
	}

	public void setHHolidays(java.math.BigDecimal hHolidays) {
		this.hHolidays = hHolidays;
	}

	public java.math.BigDecimal getHDisease() {
		return this.hDisease;
	}

	public void setHDisease(java.math.BigDecimal hDisease) {
		this.hDisease = hDisease;
	}

	public java.math.BigDecimal getHTotal() {
		return this.hTotal;
	}

	public void setHTotal(java.math.BigDecimal hTotal) {
		this.hTotal = hTotal;
	}

	public java.lang.Short getNoLoad() {
		return this.noLoad;
	}

	public void setNoLoad(java.lang.Short noLoad) {
		this.noLoad = noLoad;
	}

	public java.math.BigDecimal getHReports() {
		return this.hReports;
	}

	public void setHReports(java.math.BigDecimal hReports) {
		this.hReports = hReports;
	}

	public java.math.BigDecimal getHWorkTot() {
		return this.hWorkTot;
	}

	public void setHWorkTot(java.math.BigDecimal hWorkTot) {
		this.hWorkTot = hWorkTot;
	}

	public java.math.BigDecimal getHWorkH() {
		return this.hWorkH;
	}

	public void setHWorkH(java.math.BigDecimal hWorkH) {
		this.hWorkH = hWorkH;
	}

	public java.math.BigDecimal getHWorkMin() {
		return this.hWorkMin;
	}

	public void setHWorkMin(java.math.BigDecimal hWorkMin) {
		this.hWorkMin = hWorkMin;
	}

	public java.math.BigDecimal getHPermitsTot() {
		return this.hPermitsTot;
	}

	public void setHPermitsTot(java.math.BigDecimal hPermitsTot) {
		this.hPermitsTot = hPermitsTot;
	}

	public java.math.BigDecimal getHPermitsH() {
		return this.hPermitsH;
	}

	public void setHPermitsH(java.math.BigDecimal hPermitsH) {
		this.hPermitsH = hPermitsH;
	}

	public java.math.BigDecimal getHPermitsMin() {
		return this.hPermitsMin;
	}

	public void setHPermitsMin(java.math.BigDecimal hPermitsMin) {
		this.hPermitsMin = hPermitsMin;
	}

	public java.math.BigDecimal getHExtra_1Tot() {
		return this.hExtra_1Tot;
	}

	public void setHExtra_1Tot(java.math.BigDecimal hExtra_1Tot) {
		this.hExtra_1Tot = hExtra_1Tot;
	}

	public java.math.BigDecimal getHExtra_2Tot() {
		return this.hExtra_2Tot;
	}

	public void setHExtra_2Tot(java.math.BigDecimal hExtra_2Tot) {
		this.hExtra_2Tot = hExtra_2Tot;
	}

	public java.math.BigDecimal getHExtra_2H() {
		return this.hExtra_2H;
	}

	public void setHExtra_2H(java.math.BigDecimal hExtra_2H) {
		this.hExtra_2H = hExtra_2H;
	}

	public java.math.BigDecimal getHExtra_2Min() {
		return this.hExtra_2Min;
	}

	public void setHExtra_2Min(java.math.BigDecimal hExtra_2Min) {
		this.hExtra_2Min = hExtra_2Min;
	}

	public java.math.BigDecimal getHExtra_3Tot() {
		return this.hExtra_3Tot;
	}

	public void setHExtra_3Tot(java.math.BigDecimal hExtra_3Tot) {
		this.hExtra_3Tot = hExtra_3Tot;
	}

	public java.math.BigDecimal getHExtra_3H() {
		return this.hExtra_3H;
	}

	public void setHExtra_3H(java.math.BigDecimal hExtra_3H) {
		this.hExtra_3H = hExtra_3H;
	}

	public java.math.BigDecimal getHExtra_3Min() {
		return this.hExtra_3Min;
	}

	public void setHExtra_3Min(java.math.BigDecimal hExtra_3Min) {
		this.hExtra_3Min = hExtra_3Min;
	}

	public java.math.BigDecimal getHHolidaysTot() {
		return this.hHolidaysTot;
	}

	public void setHHolidaysTot(java.math.BigDecimal hHolidaysTot) {
		this.hHolidaysTot = hHolidaysTot;
	}

	public java.math.BigDecimal getHHolidaysH() {
		return this.hHolidaysH;
	}

	public void setHHolidaysH(java.math.BigDecimal hHolidaysH) {
		this.hHolidaysH = hHolidaysH;
	}

	public java.math.BigDecimal getHHolidaysMin() {
		return this.hHolidaysMin;
	}

	public void setHHolidaysMin(java.math.BigDecimal hHolidaysMin) {
		this.hHolidaysMin = hHolidaysMin;
	}

	public java.math.BigDecimal getHDiseaseTot() {
		return this.hDiseaseTot;
	}

	public void setHDiseaseTot(java.math.BigDecimal hDiseaseTot) {
		this.hDiseaseTot = hDiseaseTot;
	}

	public java.math.BigDecimal getHDiseaseH() {
		return this.hDiseaseH;
	}

	public void setHDiseaseH(java.math.BigDecimal hDiseaseH) {
		this.hDiseaseH = hDiseaseH;
	}

	public java.math.BigDecimal getHDiseaseMin() {
		return this.hDiseaseMin;
	}

	public void setHDiseaseMin(java.math.BigDecimal hDiseaseMin) {
		this.hDiseaseMin = hDiseaseMin;
	}

	public java.math.BigDecimal getHTotalTot() {
		return this.hTotalTot;
	}

	public void setHTotalTot(java.math.BigDecimal hTotalTot) {
		this.hTotalTot = hTotalTot;
	}

	public java.math.BigDecimal getHTotalH() {
		return this.hTotalH;
	}

	public void setHTotalH(java.math.BigDecimal hTotalH) {
		this.hTotalH = hTotalH;
	}

	public java.math.BigDecimal getHTotalMin() {
		return this.hTotalMin;
	}

	public void setHTotalMin(java.math.BigDecimal hTotalMin) {
		this.hTotalMin = hTotalMin;
	}

	public java.math.BigDecimal getHReportsTot() {
		return this.hReportsTot;
	}

	public void setHReportsTot(java.math.BigDecimal hReportsTot) {
		this.hReportsTot = hReportsTot;
	}

	public java.math.BigDecimal getHReportsH() {
		return this.hReportsH;
	}

	public void setHReportsH(java.math.BigDecimal hReportsH) {
		this.hReportsH = hReportsH;
	}

	public java.math.BigDecimal getHReportsMin() {
		return this.hReportsMin;
	}

	public void setHReportsMin(java.math.BigDecimal hReportsMin) {
		this.hReportsMin = hReportsMin;
	}

	public java.lang.String getUsername() {
		return this.username;
	}

	public void setUsername(java.lang.String username) {
		this.username = username;
	}
}
