/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Drm extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 1235701565;

	/**
	 * The reference instance of <code>drm</code>
	 */
	public static final Drm DRM = new Drm();

	/**
	 * No further instances allowed
	 */
	private Drm() {
		super("drm");
	}

	@Override
	public final java.util.List<org.jooq.Sequence<?>> getSequences() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final java.util.List<org.jooq.Sequence<?>> getSequences0() {
		return java.util.Arrays.<org.jooq.Sequence<?>>asList(
			com.sonicle.webtop.drm.jooq.Sequences.SEQ_BUSINESS_TRIPS,
			com.sonicle.webtop.drm.jooq.Sequences.SEQ_COMPANIES,
			com.sonicle.webtop.drm.jooq.Sequences.SEQ_COMPANIES_USERS,
			com.sonicle.webtop.drm.jooq.Sequences.SEQ_DOC_STATUSES,
			com.sonicle.webtop.drm.jooq.Sequences.SEQ_DOC_STATUSES_GROUPS,
			com.sonicle.webtop.drm.jooq.Sequences.SEQ_EXPENSE_NOTE_COSTS,
			com.sonicle.webtop.drm.jooq.Sequences.SEQ_EXPENSE_NOTE_DOCUMENTS,
			com.sonicle.webtop.drm.jooq.Sequences.SEQ_EXPENSE_NOTE_ROW_DETAILS,
			com.sonicle.webtop.drm.jooq.Sequences.SEQ_EXPENSE_NOTE_ROW_DOCUMENTS,
			com.sonicle.webtop.drm.jooq.Sequences.SEQ_EXPENSE_NOTE_ROWS,
			com.sonicle.webtop.drm.jooq.Sequences.SEQ_EXPENSE_NOTES,
			com.sonicle.webtop.drm.jooq.Sequences.SEQ_FOLDERS_GROUPS,
			com.sonicle.webtop.drm.jooq.Sequences.SEQ_GROUPS_USERS,
			com.sonicle.webtop.drm.jooq.Sequences.SEQ_HOLIDAY_3aDAY,
			com.sonicle.webtop.drm.jooq.Sequences.SEQ_PERSON_IN_CHARGE,
			com.sonicle.webtop.drm.jooq.Sequences.SEQ_PROFILES_MASTERDATA,
			com.sonicle.webtop.drm.jooq.Sequences.SEQ_PROFILES_MEMBERS,
			com.sonicle.webtop.drm.jooq.Sequences.SEQ_PROFILES_SUPERVISED_USERS,
			com.sonicle.webtop.drm.jooq.Sequences.SEQ_PROFILES_USERS,
			com.sonicle.webtop.drm.jooq.Sequences.SEQ_TIMETABLE_MOVEMENTS,
			com.sonicle.webtop.drm.jooq.Sequences.SEQ_TIMETABLE_REQUESTS_HOLIDAY,
			com.sonicle.webtop.drm.jooq.Sequences.SEQ_TIMETABLE_USER_HOURS,
			com.sonicle.webtop.drm.jooq.Sequences.SEQ_USER_FOR_PERSON_IN_CHARGE,
			com.sonicle.webtop.drm.jooq.Sequences.SEQ_WORK_REPORT_DETAILS,
			com.sonicle.webtop.drm.jooq.Sequences.SEQ_WORK_REPORTS,
			com.sonicle.webtop.drm.jooq.Sequences.SEQ_WORK_REPORTS_COUNT,
			com.sonicle.webtop.drm.jooq.Sequences.SEQ_WORK_REPORTS_SETTINGS,
			com.sonicle.webtop.drm.jooq.Sequences.SEQ_WORK_TYPES);
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.sonicle.webtop.drm.jooq.tables.BusinessTrips.BUSINESS_TRIPS,
			com.sonicle.webtop.drm.jooq.tables.Companies.COMPANIES,
			com.sonicle.webtop.drm.jooq.tables.CompaniesPictures.COMPANIES_PICTURES,
			com.sonicle.webtop.drm.jooq.tables.CompaniesUsers.COMPANIES_USERS,
			com.sonicle.webtop.drm.jooq.tables.DocStatuses.DOC_STATUSES,
			com.sonicle.webtop.drm.jooq.tables.DocStatusesGroups.DOC_STATUSES_GROUPS,
			com.sonicle.webtop.drm.jooq.tables.EnabledPrograms.ENABLED_PROGRAMS,
			com.sonicle.webtop.drm.jooq.tables.ExpenseNoteCostTypes.EXPENSE_NOTE_COST_TYPES,
			com.sonicle.webtop.drm.jooq.tables.ExpenseNoteCosts.EXPENSE_NOTE_COSTS,
			com.sonicle.webtop.drm.jooq.tables.ExpenseNoteDocumentLinks.EXPENSE_NOTE_DOCUMENT_LINKS,
			com.sonicle.webtop.drm.jooq.tables.ExpenseNoteDocuments.EXPENSE_NOTE_DOCUMENTS,
			com.sonicle.webtop.drm.jooq.tables.ExpenseNoteRowDetails.EXPENSE_NOTE_ROW_DETAILS,
			com.sonicle.webtop.drm.jooq.tables.ExpenseNoteRowDocumentLinks.EXPENSE_NOTE_ROW_DOCUMENT_LINKS,
			com.sonicle.webtop.drm.jooq.tables.ExpenseNoteRowDocuments.EXPENSE_NOTE_ROW_DOCUMENTS,
			com.sonicle.webtop.drm.jooq.tables.ExpenseNoteRows.EXPENSE_NOTE_ROWS,
			com.sonicle.webtop.drm.jooq.tables.ExpenseNoteSettings.EXPENSE_NOTE_SETTINGS,
			com.sonicle.webtop.drm.jooq.tables.ExpenseNotes.EXPENSE_NOTES,
			com.sonicle.webtop.drm.jooq.tables.Folders.FOLDERS,
			com.sonicle.webtop.drm.jooq.tables.FoldersGroups.FOLDERS_GROUPS,
			com.sonicle.webtop.drm.jooq.tables.Groups.GROUPS,
			com.sonicle.webtop.drm.jooq.tables.GroupsUsers.GROUPS_USERS,
			com.sonicle.webtop.drm.jooq.tables.HolidayDate.HOLIDAY_DATE,
			com.sonicle.webtop.drm.jooq.tables.PersonInCharge.PERSON_IN_CHARGE,
			com.sonicle.webtop.drm.jooq.tables.Profiles.PROFILES,
			com.sonicle.webtop.drm.jooq.tables.ProfilesMasterdata.PROFILES_MASTERDATA,
			com.sonicle.webtop.drm.jooq.tables.ProfilesMembers.PROFILES_MEMBERS,
			com.sonicle.webtop.drm.jooq.tables.ProfilesSupervisedUsers.PROFILES_SUPERVISED_USERS,
			com.sonicle.webtop.drm.jooq.tables.TimetableAttendancesheet.TIMETABLE_ATTENDANCESHEET,
			com.sonicle.webtop.drm.jooq.tables.TimetableMovements.TIMETABLE_MOVEMENTS,
			com.sonicle.webtop.drm.jooq.tables.TimetableRequestsHoliday.TIMETABLE_REQUESTS_HOLIDAY,
			com.sonicle.webtop.drm.jooq.tables.TimetableUserHours.TIMETABLE_USER_HOURS,
			com.sonicle.webtop.drm.jooq.tables.UserForPersonInCharge.USER_FOR_PERSON_IN_CHARGE,
			com.sonicle.webtop.drm.jooq.tables.WorkReports.WORK_REPORTS,
			com.sonicle.webtop.drm.jooq.tables.WorkReportsAttachments.WORK_REPORTS_ATTACHMENTS,
			com.sonicle.webtop.drm.jooq.tables.WorkReportsRows.WORK_REPORTS_ROWS,
			com.sonicle.webtop.drm.jooq.tables.WorkReportsSettings.WORK_REPORTS_SETTINGS,
			com.sonicle.webtop.drm.jooq.tables.WorkTypes.WORK_TYPES);
	}
}
