/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq;

/**
 * Convenience access to all tables in drm
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table drm.business_trips
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.BusinessTrips BUSINESS_TRIPS = com.sonicle.webtop.drm.jooq.tables.BusinessTrips.BUSINESS_TRIPS;

	/**
	 * The table drm.companies
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.Companies COMPANIES = com.sonicle.webtop.drm.jooq.tables.Companies.COMPANIES;

	/**
	 * The table drm.companies_users
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.CompaniesUsers COMPANIES_USERS = com.sonicle.webtop.drm.jooq.tables.CompaniesUsers.COMPANIES_USERS;

	/**
	 * The table drm.doc_statuses
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.DocStatuses DOC_STATUSES = com.sonicle.webtop.drm.jooq.tables.DocStatuses.DOC_STATUSES;

	/**
	 * The table drm.doc_statuses_groups
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.DocStatusesGroups DOC_STATUSES_GROUPS = com.sonicle.webtop.drm.jooq.tables.DocStatusesGroups.DOC_STATUSES_GROUPS;

	/**
	 * The table drm.enabled_programs
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.EnabledPrograms ENABLED_PROGRAMS = com.sonicle.webtop.drm.jooq.tables.EnabledPrograms.ENABLED_PROGRAMS;

	/**
	 * The table drm.folders
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.Folders FOLDERS = com.sonicle.webtop.drm.jooq.tables.Folders.FOLDERS;

	/**
	 * The table drm.folders_groups
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.FoldersGroups FOLDERS_GROUPS = com.sonicle.webtop.drm.jooq.tables.FoldersGroups.FOLDERS_GROUPS;

	/**
	 * The table drm.groups
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.Groups GROUPS = com.sonicle.webtop.drm.jooq.tables.Groups.GROUPS;

	/**
	 * The table drm.groups_users
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.GroupsUsers GROUPS_USERS = com.sonicle.webtop.drm.jooq.tables.GroupsUsers.GROUPS_USERS;

	/**
	 * The table drm.profiles
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.Profiles PROFILES = com.sonicle.webtop.drm.jooq.tables.Profiles.PROFILES;

	/**
	 * The table drm.profiles_masterdata
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.ProfilesMasterdata PROFILES_MASTERDATA = com.sonicle.webtop.drm.jooq.tables.ProfilesMasterdata.PROFILES_MASTERDATA;

	/**
	 * The table drm.profiles_supervised_users
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.ProfilesSupervisedUsers PROFILES_SUPERVISED_USERS = com.sonicle.webtop.drm.jooq.tables.ProfilesSupervisedUsers.PROFILES_SUPERVISED_USERS;

	/**
	 * The table drm.profiles_users
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.ProfilesUsers PROFILES_USERS = com.sonicle.webtop.drm.jooq.tables.ProfilesUsers.PROFILES_USERS;

	/**
	 * The table drm.work_reports
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.WorkReports WORK_REPORTS = com.sonicle.webtop.drm.jooq.tables.WorkReports.WORK_REPORTS;

	/**
	 * The table drm.work_reports_attachments
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.WorkReportsAttachments WORK_REPORTS_ATTACHMENTS = com.sonicle.webtop.drm.jooq.tables.WorkReportsAttachments.WORK_REPORTS_ATTACHMENTS;

	/**
	 * The table drm.work_reports_details
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.WorkReportsDetails WORK_REPORTS_DETAILS = com.sonicle.webtop.drm.jooq.tables.WorkReportsDetails.WORK_REPORTS_DETAILS;

	/**
	 * The table drm.work_reports_settings
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.WorkReportsSettings WORK_REPORTS_SETTINGS = com.sonicle.webtop.drm.jooq.tables.WorkReportsSettings.WORK_REPORTS_SETTINGS;

	/**
	 * The table drm.work_types
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.WorkTypes WORK_TYPES = com.sonicle.webtop.drm.jooq.tables.WorkTypes.WORK_TYPES;
}
