/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BusinessTripsRecord extends org.jooq.impl.UpdatableRecordImpl<com.sonicle.webtop.drm.jooq.tables.records.BusinessTripsRecord> implements org.jooq.Record5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 1375499071;

	/**
	 * Setter for <code>drm.business_trips.business_trip_id</code>.
	 */
	public void setBusinessTripId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>drm.business_trips.business_trip_id</code>.
	 */
	public java.lang.Integer getBusinessTripId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>drm.business_trips.domain_id</code>.
	 */
	public void setDomainId(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>drm.business_trips.domain_id</code>.
	 */
	public java.lang.String getDomainId() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>drm.business_trips.revision_status</code>.
	 */
	public void setRevisionStatus(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>drm.business_trips.revision_status</code>.
	 */
	public java.lang.String getRevisionStatus() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>drm.business_trips.external_id</code>.
	 */
	public void setExternalId(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>drm.business_trips.external_id</code>.
	 */
	public java.lang.String getExternalId() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>drm.business_trips.description</code>.
	 */
	public void setDescription(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>drm.business_trips.description</code>.
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.sonicle.webtop.drm.jooq.tables.BusinessTrips.BUSINESS_TRIPS.BUSINESS_TRIP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.sonicle.webtop.drm.jooq.tables.BusinessTrips.BUSINESS_TRIPS.DOMAIN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.sonicle.webtop.drm.jooq.tables.BusinessTrips.BUSINESS_TRIPS.REVISION_STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.sonicle.webtop.drm.jooq.tables.BusinessTrips.BUSINESS_TRIPS.EXTERNAL_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.sonicle.webtop.drm.jooq.tables.BusinessTrips.BUSINESS_TRIPS.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getBusinessTripId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getDomainId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getRevisionStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getExternalId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusinessTripsRecord value1(java.lang.Integer value) {
		setBusinessTripId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusinessTripsRecord value2(java.lang.String value) {
		setDomainId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusinessTripsRecord value3(java.lang.String value) {
		setRevisionStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusinessTripsRecord value4(java.lang.String value) {
		setExternalId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusinessTripsRecord value5(java.lang.String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusinessTripsRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BusinessTripsRecord
	 */
	public BusinessTripsRecord() {
		super(com.sonicle.webtop.drm.jooq.tables.BusinessTrips.BUSINESS_TRIPS);
	}

	/**
	 * Create a detached, initialised BusinessTripsRecord
	 */
	public BusinessTripsRecord(java.lang.Integer businessTripId, java.lang.String domainId, java.lang.String revisionStatus, java.lang.String externalId, java.lang.String description) {
		super(com.sonicle.webtop.drm.jooq.tables.BusinessTrips.BUSINESS_TRIPS);

		setValue(0, businessTripId);
		setValue(1, domainId);
		setValue(2, revisionStatus);
		setValue(3, externalId);
		setValue(4, description);
	}
}
