/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployeeHoursRecord extends org.jooq.impl.UpdatableRecordImpl<com.sonicle.webtop.drm.jooq.tables.records.EmployeeHoursRecord> {

	private static final long serialVersionUID = -525610802;

	/**
	 * Setter for <code>drm.employee_hours.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>drm.employee_hours.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>drm.employee_hours.domain_id</code>.
	 */
	public void setDomainId(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>drm.employee_hours.domain_id</code>.
	 */
	public java.lang.String getDomainId() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>drm.employee_hours.employee_profile_id</code>.
	 */
	public void setEmployeeProfileId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>drm.employee_hours.employee_profile_id</code>.
	 */
	public java.lang.Integer getEmployeeProfileId() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>drm.employee_hours.line_id</code>.
	 */
	public void setLineId(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>drm.employee_hours.line_id</code>.
	 */
	public java.lang.Integer getLineId() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>drm.employee_hours.1_e</code>.
	 */
	public void set_1E(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>drm.employee_hours.1_e</code>.
	 */
	public java.lang.String get_1E() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>drm.employee_hours.1_u</code>.
	 */
	public void set_1U(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>drm.employee_hours.1_u</code>.
	 */
	public java.lang.String get_1U() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>drm.employee_hours.1_h</code>.
	 */
	public void set_1H(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>drm.employee_hours.1_h</code>.
	 */
	public java.lang.String get_1H() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>drm.employee_hours.2_e</code>.
	 */
	public void set_2E(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>drm.employee_hours.2_e</code>.
	 */
	public java.lang.String get_2E() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>drm.employee_hours.2_u</code>.
	 */
	public void set_2U(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>drm.employee_hours.2_u</code>.
	 */
	public java.lang.String get_2U() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>drm.employee_hours.2_h</code>.
	 */
	public void set_2H(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>drm.employee_hours.2_h</code>.
	 */
	public java.lang.String get_2H() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>drm.employee_hours.3_e</code>.
	 */
	public void set_3E(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>drm.employee_hours.3_e</code>.
	 */
	public java.lang.String get_3E() {
		return (java.lang.String) getValue(10);
	}

	/**
	 * Setter for <code>drm.employee_hours.3_u</code>.
	 */
	public void set_3U(java.lang.String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>drm.employee_hours.3_u</code>.
	 */
	public java.lang.String get_3U() {
		return (java.lang.String) getValue(11);
	}

	/**
	 * Setter for <code>drm.employee_hours.3_h</code>.
	 */
	public void set_3H(java.lang.String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>drm.employee_hours.3_h</code>.
	 */
	public java.lang.String get_3H() {
		return (java.lang.String) getValue(12);
	}

	/**
	 * Setter for <code>drm.employee_hours.4_e</code>.
	 */
	public void set_4E(java.lang.String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>drm.employee_hours.4_e</code>.
	 */
	public java.lang.String get_4E() {
		return (java.lang.String) getValue(13);
	}

	/**
	 * Setter for <code>drm.employee_hours.4_u</code>.
	 */
	public void set_4U(java.lang.String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>drm.employee_hours.4_u</code>.
	 */
	public java.lang.String get_4U() {
		return (java.lang.String) getValue(14);
	}

	/**
	 * Setter for <code>drm.employee_hours.4_h</code>.
	 */
	public void set_4H(java.lang.String value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>drm.employee_hours.4_h</code>.
	 */
	public java.lang.String get_4H() {
		return (java.lang.String) getValue(15);
	}

	/**
	 * Setter for <code>drm.employee_hours.5_e</code>.
	 */
	public void set_5E(java.lang.String value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>drm.employee_hours.5_e</code>.
	 */
	public java.lang.String get_5E() {
		return (java.lang.String) getValue(16);
	}

	/**
	 * Setter for <code>drm.employee_hours.5_u</code>.
	 */
	public void set_5U(java.lang.String value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>drm.employee_hours.5_u</code>.
	 */
	public java.lang.String get_5U() {
		return (java.lang.String) getValue(17);
	}

	/**
	 * Setter for <code>drm.employee_hours.5_h</code>.
	 */
	public void set_5H(java.lang.String value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>drm.employee_hours.5_h</code>.
	 */
	public java.lang.String get_5H() {
		return (java.lang.String) getValue(18);
	}

	/**
	 * Setter for <code>drm.employee_hours.6_e</code>.
	 */
	public void set_6E(java.lang.String value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>drm.employee_hours.6_e</code>.
	 */
	public java.lang.String get_6E() {
		return (java.lang.String) getValue(19);
	}

	/**
	 * Setter for <code>drm.employee_hours.6_u</code>.
	 */
	public void set_6U(java.lang.String value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>drm.employee_hours.6_u</code>.
	 */
	public java.lang.String get_6U() {
		return (java.lang.String) getValue(20);
	}

	/**
	 * Setter for <code>drm.employee_hours.6_h</code>.
	 */
	public void set_6H(java.lang.String value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>drm.employee_hours.6_h</code>.
	 */
	public java.lang.String get_6H() {
		return (java.lang.String) getValue(21);
	}

	/**
	 * Setter for <code>drm.employee_hours.7_e</code>.
	 */
	public void set_7E(java.lang.String value) {
		setValue(22, value);
	}

	/**
	 * Getter for <code>drm.employee_hours.7_e</code>.
	 */
	public java.lang.String get_7E() {
		return (java.lang.String) getValue(22);
	}

	/**
	 * Setter for <code>drm.employee_hours.7_u</code>.
	 */
	public void set_7U(java.lang.String value) {
		setValue(23, value);
	}

	/**
	 * Getter for <code>drm.employee_hours.7_u</code>.
	 */
	public java.lang.String get_7U() {
		return (java.lang.String) getValue(23);
	}

	/**
	 * Setter for <code>drm.employee_hours.7_h</code>.
	 */
	public void set_7H(java.lang.String value) {
		setValue(24, value);
	}

	/**
	 * Getter for <code>drm.employee_hours.7_h</code>.
	 */
	public java.lang.String get_7H() {
		return (java.lang.String) getValue(24);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EmployeeHoursRecord
	 */
	public EmployeeHoursRecord() {
		super(com.sonicle.webtop.drm.jooq.tables.EmployeeHours.EMPLOYEE_HOURS);
	}

	/**
	 * Create a detached, initialised EmployeeHoursRecord
	 */
	public EmployeeHoursRecord(java.lang.Integer id, java.lang.String domainId, java.lang.Integer employeeProfileId, java.lang.Integer lineId, java.lang.String _1E, java.lang.String _1U, java.lang.String _1H, java.lang.String _2E, java.lang.String _2U, java.lang.String _2H, java.lang.String _3E, java.lang.String _3U, java.lang.String _3H, java.lang.String _4E, java.lang.String _4U, java.lang.String _4H, java.lang.String _5E, java.lang.String _5U, java.lang.String _5H, java.lang.String _6E, java.lang.String _6U, java.lang.String _6H, java.lang.String _7E, java.lang.String _7U, java.lang.String _7H) {
		super(com.sonicle.webtop.drm.jooq.tables.EmployeeHours.EMPLOYEE_HOURS);

		setValue(0, id);
		setValue(1, domainId);
		setValue(2, employeeProfileId);
		setValue(3, lineId);
		setValue(4, _1E);
		setValue(5, _1U);
		setValue(6, _1H);
		setValue(7, _2E);
		setValue(8, _2U);
		setValue(9, _2H);
		setValue(10, _3E);
		setValue(11, _3U);
		setValue(12, _3H);
		setValue(13, _4E);
		setValue(14, _4U);
		setValue(15, _4H);
		setValue(16, _5E);
		setValue(17, _5U);
		setValue(18, _5H);
		setValue(19, _6E);
		setValue(20, _6U);
		setValue(21, _6H);
		setValue(22, _7E);
		setValue(23, _7U);
		setValue(24, _7H);
	}
}
