/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExpenseNoteCostsRecord extends org.jooq.impl.UpdatableRecordImpl<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteCostsRecord> implements org.jooq.Record11<java.math.BigInteger, java.lang.String, java.lang.String, java.math.BigInteger, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 1715439933;

	/**
	 * Setter for <code>drm.expense_note_costs.type_id</code>.
	 */
	public void setTypeId(java.math.BigInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>drm.expense_note_costs.type_id</code>.
	 */
	public java.math.BigInteger getTypeId() {
		return (java.math.BigInteger) getValue(0);
	}

	/**
	 * Setter for <code>drm.expense_note_costs.description</code>.
	 */
	public void setDescription(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>drm.expense_note_costs.description</code>.
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>drm.expense_note_costs.max_import</code>.
	 */
	public void setMaxImport(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>drm.expense_note_costs.max_import</code>.
	 */
	public java.lang.String getMaxImport() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>drm.expense_note_costs.type_cost</code>.
	 */
	public void setTypeCost(java.math.BigInteger value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>drm.expense_note_costs.type_cost</code>.
	 */
	public java.math.BigInteger getTypeCost() {
		return (java.math.BigInteger) getValue(3);
	}

	/**
	 * Setter for <code>drm.expense_note_costs.type_cost_present</code>.
	 */
	public void setTypeCostPresent(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>drm.expense_note_costs.type_cost_present</code>.
	 */
	public java.lang.String getTypeCostPresent() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>drm.expense_note_costs.type_cost_km</code>.
	 */
	public void setTypeCostKm(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>drm.expense_note_costs.type_cost_km</code>.
	 */
	public java.lang.String getTypeCostKm() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>drm.expense_note_costs.domain_id</code>.
	 */
	public void setDomainId(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>drm.expense_note_costs.domain_id</code>.
	 */
	public java.lang.String getDomainId() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>drm.expense_note_costs.consumption</code>.
	 */
	public void setConsumption(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>drm.expense_note_costs.consumption</code>.
	 */
	public java.lang.String getConsumption() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>drm.expense_note_costs.type_cost_advance</code>.
	 */
	public void setTypeCostAdvance(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>drm.expense_note_costs.type_cost_advance</code>.
	 */
	public java.lang.String getTypeCostAdvance() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>drm.expense_note_costs.type_cost_unlock_change</code>.
	 */
	public void setTypeCostUnlockChange(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>drm.expense_note_costs.type_cost_unlock_change</code>.
	 */
	public java.lang.String getTypeCostUnlockChange() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>drm.expense_note_costs.type_cost_person</code>.
	 */
	public void setTypeCostPerson(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>drm.expense_note_costs.type_cost_person</code>.
	 */
	public java.lang.String getTypeCostPerson() {
		return (java.lang.String) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.math.BigInteger> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.math.BigInteger, java.lang.String, java.lang.String, java.math.BigInteger, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.math.BigInteger, java.lang.String, java.lang.String, java.math.BigInteger, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigInteger> field1() {
		return com.sonicle.webtop.drm.jooq.tables.ExpenseNoteCosts.EXPENSE_NOTE_COSTS.TYPE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.sonicle.webtop.drm.jooq.tables.ExpenseNoteCosts.EXPENSE_NOTE_COSTS.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.sonicle.webtop.drm.jooq.tables.ExpenseNoteCosts.EXPENSE_NOTE_COSTS.MAX_IMPORT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigInteger> field4() {
		return com.sonicle.webtop.drm.jooq.tables.ExpenseNoteCosts.EXPENSE_NOTE_COSTS.TYPE_COST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.sonicle.webtop.drm.jooq.tables.ExpenseNoteCosts.EXPENSE_NOTE_COSTS.TYPE_COST_PRESENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.sonicle.webtop.drm.jooq.tables.ExpenseNoteCosts.EXPENSE_NOTE_COSTS.TYPE_COST_KM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.sonicle.webtop.drm.jooq.tables.ExpenseNoteCosts.EXPENSE_NOTE_COSTS.DOMAIN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.sonicle.webtop.drm.jooq.tables.ExpenseNoteCosts.EXPENSE_NOTE_COSTS.CONSUMPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return com.sonicle.webtop.drm.jooq.tables.ExpenseNoteCosts.EXPENSE_NOTE_COSTS.TYPE_COST_ADVANCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return com.sonicle.webtop.drm.jooq.tables.ExpenseNoteCosts.EXPENSE_NOTE_COSTS.TYPE_COST_UNLOCK_CHANGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field11() {
		return com.sonicle.webtop.drm.jooq.tables.ExpenseNoteCosts.EXPENSE_NOTE_COSTS.TYPE_COST_PERSON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigInteger value1() {
		return getTypeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getMaxImport();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigInteger value4() {
		return getTypeCost();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getTypeCostPresent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getTypeCostKm();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getDomainId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getConsumption();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getTypeCostAdvance();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getTypeCostUnlockChange();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value11() {
		return getTypeCostPerson();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpenseNoteCostsRecord value1(java.math.BigInteger value) {
		setTypeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpenseNoteCostsRecord value2(java.lang.String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpenseNoteCostsRecord value3(java.lang.String value) {
		setMaxImport(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpenseNoteCostsRecord value4(java.math.BigInteger value) {
		setTypeCost(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpenseNoteCostsRecord value5(java.lang.String value) {
		setTypeCostPresent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpenseNoteCostsRecord value6(java.lang.String value) {
		setTypeCostKm(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpenseNoteCostsRecord value7(java.lang.String value) {
		setDomainId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpenseNoteCostsRecord value8(java.lang.String value) {
		setConsumption(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpenseNoteCostsRecord value9(java.lang.String value) {
		setTypeCostAdvance(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpenseNoteCostsRecord value10(java.lang.String value) {
		setTypeCostUnlockChange(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpenseNoteCostsRecord value11(java.lang.String value) {
		setTypeCostPerson(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpenseNoteCostsRecord values(java.math.BigInteger value1, java.lang.String value2, java.lang.String value3, java.math.BigInteger value4, java.lang.String value5, java.lang.String value6, java.lang.String value7, java.lang.String value8, java.lang.String value9, java.lang.String value10, java.lang.String value11) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ExpenseNoteCostsRecord
	 */
	public ExpenseNoteCostsRecord() {
		super(com.sonicle.webtop.drm.jooq.tables.ExpenseNoteCosts.EXPENSE_NOTE_COSTS);
	}

	/**
	 * Create a detached, initialised ExpenseNoteCostsRecord
	 */
	public ExpenseNoteCostsRecord(java.math.BigInteger typeId, java.lang.String description, java.lang.String maxImport, java.math.BigInteger typeCost, java.lang.String typeCostPresent, java.lang.String typeCostKm, java.lang.String domainId, java.lang.String consumption, java.lang.String typeCostAdvance, java.lang.String typeCostUnlockChange, java.lang.String typeCostPerson) {
		super(com.sonicle.webtop.drm.jooq.tables.ExpenseNoteCosts.EXPENSE_NOTE_COSTS);

		setValue(0, typeId);
		setValue(1, description);
		setValue(2, maxImport);
		setValue(3, typeCost);
		setValue(4, typeCostPresent);
		setValue(5, typeCostKm);
		setValue(6, domainId);
		setValue(7, consumption);
		setValue(8, typeCostAdvance);
		setValue(9, typeCostUnlockChange);
		setValue(10, typeCostPerson);
	}
}
