/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExpenseNoteDocumentsRecord extends org.jooq.impl.UpdatableRecordImpl<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteDocumentsRecord> implements org.jooq.Record6<java.math.BigInteger, java.lang.Long, java.lang.String, java.math.BigInteger, org.joda.time.DateTime, java.lang.String> {

	private static final long serialVersionUID = 705845215;

	/**
	 * Setter for <code>drm.expense_note_documents.expense_note_document_id</code>.
	 */
	public void setExpenseNoteDocumentId(java.math.BigInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>drm.expense_note_documents.expense_note_document_id</code>.
	 */
	public java.math.BigInteger getExpenseNoteDocumentId() {
		return (java.math.BigInteger) getValue(0);
	}

	/**
	 * Setter for <code>drm.expense_note_documents.file</code>.
	 */
	public void setFile(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>drm.expense_note_documents.file</code>.
	 */
	public java.lang.Long getFile() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>drm.expense_note_documents.filename</code>.
	 */
	public void setFilename(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>drm.expense_note_documents.filename</code>.
	 */
	public java.lang.String getFilename() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>drm.expense_note_documents.expense_note_id</code>.
	 */
	public void setExpenseNoteId(java.math.BigInteger value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>drm.expense_note_documents.expense_note_id</code>.
	 */
	public java.math.BigInteger getExpenseNoteId() {
		return (java.math.BigInteger) getValue(3);
	}

	/**
	 * Setter for <code>drm.expense_note_documents.revision</code>.
	 */
	public void setRevision(org.joda.time.DateTime value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>drm.expense_note_documents.revision</code>.
	 */
	public org.joda.time.DateTime getRevision() {
		return (org.joda.time.DateTime) getValue(4);
	}

	/**
	 * Setter for <code>drm.expense_note_documents.operator_id_lock_file</code>.
	 */
	public void setOperatorIdLockFile(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>drm.expense_note_documents.operator_id_lock_file</code>.
	 */
	public java.lang.String getOperatorIdLockFile() {
		return (java.lang.String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.math.BigInteger> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.math.BigInteger, java.lang.Long, java.lang.String, java.math.BigInteger, org.joda.time.DateTime, java.lang.String> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.math.BigInteger, java.lang.Long, java.lang.String, java.math.BigInteger, org.joda.time.DateTime, java.lang.String> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigInteger> field1() {
		return com.sonicle.webtop.drm.jooq.tables.ExpenseNoteDocuments.EXPENSE_NOTE_DOCUMENTS.EXPENSE_NOTE_DOCUMENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.sonicle.webtop.drm.jooq.tables.ExpenseNoteDocuments.EXPENSE_NOTE_DOCUMENTS.FILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.sonicle.webtop.drm.jooq.tables.ExpenseNoteDocuments.EXPENSE_NOTE_DOCUMENTS.FILENAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigInteger> field4() {
		return com.sonicle.webtop.drm.jooq.tables.ExpenseNoteDocuments.EXPENSE_NOTE_DOCUMENTS.EXPENSE_NOTE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field5() {
		return com.sonicle.webtop.drm.jooq.tables.ExpenseNoteDocuments.EXPENSE_NOTE_DOCUMENTS.REVISION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.sonicle.webtop.drm.jooq.tables.ExpenseNoteDocuments.EXPENSE_NOTE_DOCUMENTS.OPERATOR_ID_LOCK_FILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigInteger value1() {
		return getExpenseNoteDocumentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getFile();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getFilename();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigInteger value4() {
		return getExpenseNoteId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value5() {
		return getRevision();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getOperatorIdLockFile();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpenseNoteDocumentsRecord value1(java.math.BigInteger value) {
		setExpenseNoteDocumentId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpenseNoteDocumentsRecord value2(java.lang.Long value) {
		setFile(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpenseNoteDocumentsRecord value3(java.lang.String value) {
		setFilename(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpenseNoteDocumentsRecord value4(java.math.BigInteger value) {
		setExpenseNoteId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpenseNoteDocumentsRecord value5(org.joda.time.DateTime value) {
		setRevision(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpenseNoteDocumentsRecord value6(java.lang.String value) {
		setOperatorIdLockFile(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpenseNoteDocumentsRecord values(java.math.BigInteger value1, java.lang.Long value2, java.lang.String value3, java.math.BigInteger value4, org.joda.time.DateTime value5, java.lang.String value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ExpenseNoteDocumentsRecord
	 */
	public ExpenseNoteDocumentsRecord() {
		super(com.sonicle.webtop.drm.jooq.tables.ExpenseNoteDocuments.EXPENSE_NOTE_DOCUMENTS);
	}

	/**
	 * Create a detached, initialised ExpenseNoteDocumentsRecord
	 */
	public ExpenseNoteDocumentsRecord(java.math.BigInteger expenseNoteDocumentId, java.lang.Long file, java.lang.String filename, java.math.BigInteger expenseNoteId, org.joda.time.DateTime revision, java.lang.String operatorIdLockFile) {
		super(com.sonicle.webtop.drm.jooq.tables.ExpenseNoteDocuments.EXPENSE_NOTE_DOCUMENTS);

		setValue(0, expenseNoteDocumentId);
		setValue(1, file);
		setValue(2, filename);
		setValue(3, expenseNoteId);
		setValue(4, revision);
		setValue(5, operatorIdLockFile);
	}
}
