/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExpenseNoteRowDocumentsRecord extends org.jooq.impl.UpdatableRecordImpl<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteRowDocumentsRecord> implements org.jooq.Record9<java.math.BigInteger, java.math.BigInteger, org.joda.time.DateTime, java.lang.Long, java.lang.String, java.math.BigInteger, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -1277336048;

	/**
	 * Setter for <code>drm.expense_note_row_documents.expense_note_row_document_id</code>.
	 */
	public void setExpenseNoteRowDocumentId(java.math.BigInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>drm.expense_note_row_documents.expense_note_row_document_id</code>.
	 */
	public java.math.BigInteger getExpenseNoteRowDocumentId() {
		return (java.math.BigInteger) getValue(0);
	}

	/**
	 * Setter for <code>drm.expense_note_row_documents.expense_note_row_detail_id</code>.
	 */
	public void setExpenseNoteRowDetailId(java.math.BigInteger value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>drm.expense_note_row_documents.expense_note_row_detail_id</code>.
	 */
	public java.math.BigInteger getExpenseNoteRowDetailId() {
		return (java.math.BigInteger) getValue(1);
	}

	/**
	 * Setter for <code>drm.expense_note_row_documents.revision</code>.
	 */
	public void setRevision(org.joda.time.DateTime value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>drm.expense_note_row_documents.revision</code>.
	 */
	public org.joda.time.DateTime getRevision() {
		return (org.joda.time.DateTime) getValue(2);
	}

	/**
	 * Setter for <code>drm.expense_note_row_documents.file</code>.
	 */
	public void setFile(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>drm.expense_note_row_documents.file</code>.
	 */
	public java.lang.Long getFile() {
		return (java.lang.Long) getValue(3);
	}

	/**
	 * Setter for <code>drm.expense_note_row_documents.filename</code>.
	 */
	public void setFilename(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>drm.expense_note_row_documents.filename</code>.
	 */
	public java.lang.String getFilename() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>drm.expense_note_row_documents.expense_note_id</code>.
	 */
	public void setExpenseNoteId(java.math.BigInteger value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>drm.expense_note_row_documents.expense_note_id</code>.
	 */
	public java.math.BigInteger getExpenseNoteId() {
		return (java.math.BigInteger) getValue(5);
	}

	/**
	 * Setter for <code>drm.expense_note_row_documents.operator_id</code>.
	 */
	public void setOperatorId(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>drm.expense_note_row_documents.operator_id</code>.
	 */
	public java.lang.String getOperatorId() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>drm.expense_note_row_documents.domain_id</code>.
	 */
	public void setDomainId(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>drm.expense_note_row_documents.domain_id</code>.
	 */
	public java.lang.String getDomainId() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>drm.expense_note_row_documents.operator_id_lock_file</code>.
	 */
	public void setOperatorIdLockFile(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>drm.expense_note_row_documents.operator_id_lock_file</code>.
	 */
	public java.lang.String getOperatorIdLockFile() {
		return (java.lang.String) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.math.BigInteger> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.math.BigInteger, java.math.BigInteger, org.joda.time.DateTime, java.lang.Long, java.lang.String, java.math.BigInteger, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.math.BigInteger, java.math.BigInteger, org.joda.time.DateTime, java.lang.Long, java.lang.String, java.math.BigInteger, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigInteger> field1() {
		return com.sonicle.webtop.drm.jooq.tables.ExpenseNoteRowDocuments.EXPENSE_NOTE_ROW_DOCUMENTS.EXPENSE_NOTE_ROW_DOCUMENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigInteger> field2() {
		return com.sonicle.webtop.drm.jooq.tables.ExpenseNoteRowDocuments.EXPENSE_NOTE_ROW_DOCUMENTS.EXPENSE_NOTE_ROW_DETAIL_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field3() {
		return com.sonicle.webtop.drm.jooq.tables.ExpenseNoteRowDocuments.EXPENSE_NOTE_ROW_DOCUMENTS.REVISION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return com.sonicle.webtop.drm.jooq.tables.ExpenseNoteRowDocuments.EXPENSE_NOTE_ROW_DOCUMENTS.FILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.sonicle.webtop.drm.jooq.tables.ExpenseNoteRowDocuments.EXPENSE_NOTE_ROW_DOCUMENTS.FILENAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigInteger> field6() {
		return com.sonicle.webtop.drm.jooq.tables.ExpenseNoteRowDocuments.EXPENSE_NOTE_ROW_DOCUMENTS.EXPENSE_NOTE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.sonicle.webtop.drm.jooq.tables.ExpenseNoteRowDocuments.EXPENSE_NOTE_ROW_DOCUMENTS.OPERATOR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.sonicle.webtop.drm.jooq.tables.ExpenseNoteRowDocuments.EXPENSE_NOTE_ROW_DOCUMENTS.DOMAIN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return com.sonicle.webtop.drm.jooq.tables.ExpenseNoteRowDocuments.EXPENSE_NOTE_ROW_DOCUMENTS.OPERATOR_ID_LOCK_FILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigInteger value1() {
		return getExpenseNoteRowDocumentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigInteger value2() {
		return getExpenseNoteRowDetailId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value3() {
		return getRevision();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getFile();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getFilename();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigInteger value6() {
		return getExpenseNoteId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getOperatorId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getDomainId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getOperatorIdLockFile();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpenseNoteRowDocumentsRecord value1(java.math.BigInteger value) {
		setExpenseNoteRowDocumentId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpenseNoteRowDocumentsRecord value2(java.math.BigInteger value) {
		setExpenseNoteRowDetailId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpenseNoteRowDocumentsRecord value3(org.joda.time.DateTime value) {
		setRevision(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpenseNoteRowDocumentsRecord value4(java.lang.Long value) {
		setFile(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpenseNoteRowDocumentsRecord value5(java.lang.String value) {
		setFilename(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpenseNoteRowDocumentsRecord value6(java.math.BigInteger value) {
		setExpenseNoteId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpenseNoteRowDocumentsRecord value7(java.lang.String value) {
		setOperatorId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpenseNoteRowDocumentsRecord value8(java.lang.String value) {
		setDomainId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpenseNoteRowDocumentsRecord value9(java.lang.String value) {
		setOperatorIdLockFile(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpenseNoteRowDocumentsRecord values(java.math.BigInteger value1, java.math.BigInteger value2, org.joda.time.DateTime value3, java.lang.Long value4, java.lang.String value5, java.math.BigInteger value6, java.lang.String value7, java.lang.String value8, java.lang.String value9) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ExpenseNoteRowDocumentsRecord
	 */
	public ExpenseNoteRowDocumentsRecord() {
		super(com.sonicle.webtop.drm.jooq.tables.ExpenseNoteRowDocuments.EXPENSE_NOTE_ROW_DOCUMENTS);
	}

	/**
	 * Create a detached, initialised ExpenseNoteRowDocumentsRecord
	 */
	public ExpenseNoteRowDocumentsRecord(java.math.BigInteger expenseNoteRowDocumentId, java.math.BigInteger expenseNoteRowDetailId, org.joda.time.DateTime revision, java.lang.Long file, java.lang.String filename, java.math.BigInteger expenseNoteId, java.lang.String operatorId, java.lang.String domainId, java.lang.String operatorIdLockFile) {
		super(com.sonicle.webtop.drm.jooq.tables.ExpenseNoteRowDocuments.EXPENSE_NOTE_ROW_DOCUMENTS);

		setValue(0, expenseNoteRowDocumentId);
		setValue(1, expenseNoteRowDetailId);
		setValue(2, revision);
		setValue(3, file);
		setValue(4, filename);
		setValue(5, expenseNoteId);
		setValue(6, operatorId);
		setValue(7, domainId);
		setValue(8, operatorIdLockFile);
	}
}
