/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FoldersGroupsRecord extends org.jooq.impl.UpdatableRecordImpl<com.sonicle.webtop.drm.jooq.tables.records.FoldersGroupsRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 1352975669;

	/**
	 * Setter for <code>drm.folders_groups.association_id</code>.
	 */
	public void setAssociationId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>drm.folders_groups.association_id</code>.
	 */
	public java.lang.Integer getAssociationId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>drm.folders_groups.folder_id</code>.
	 */
	public void setFolderId(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>drm.folders_groups.folder_id</code>.
	 */
	public java.lang.String getFolderId() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>drm.folders_groups.group_id</code>.
	 */
	public void setGroupId(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>drm.folders_groups.group_id</code>.
	 */
	public java.lang.String getGroupId() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.sonicle.webtop.drm.jooq.tables.FoldersGroups.FOLDERS_GROUPS.ASSOCIATION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.sonicle.webtop.drm.jooq.tables.FoldersGroups.FOLDERS_GROUPS.FOLDER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.sonicle.webtop.drm.jooq.tables.FoldersGroups.FOLDERS_GROUPS.GROUP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getAssociationId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getFolderId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getGroupId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FoldersGroupsRecord value1(java.lang.Integer value) {
		setAssociationId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FoldersGroupsRecord value2(java.lang.String value) {
		setFolderId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FoldersGroupsRecord value3(java.lang.String value) {
		setGroupId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FoldersGroupsRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached FoldersGroupsRecord
	 */
	public FoldersGroupsRecord() {
		super(com.sonicle.webtop.drm.jooq.tables.FoldersGroups.FOLDERS_GROUPS);
	}

	/**
	 * Create a detached, initialised FoldersGroupsRecord
	 */
	public FoldersGroupsRecord(java.lang.Integer associationId, java.lang.String folderId, java.lang.String groupId) {
		super(com.sonicle.webtop.drm.jooq.tables.FoldersGroups.FOLDERS_GROUPS);

		setValue(0, associationId);
		setValue(1, folderId);
		setValue(2, groupId);
	}
}
