/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HolidayDateRecord extends org.jooq.impl.UpdatableRecordImpl<com.sonicle.webtop.drm.jooq.tables.records.HolidayDateRecord> implements org.jooq.Record4<java.math.BigInteger, java.lang.String, org.joda.time.DateTime, java.lang.String> {

	private static final long serialVersionUID = 227267598;

	/**
	 * Setter for <code>drm.holiday_date.holiday_date_id</code>.
	 */
	public void setHolidayDateId(java.math.BigInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>drm.holiday_date.holiday_date_id</code>.
	 */
	public java.math.BigInteger getHolidayDateId() {
		return (java.math.BigInteger) getValue(0);
	}

	/**
	 * Setter for <code>drm.holiday_date.description</code>.
	 */
	public void setDescription(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>drm.holiday_date.description</code>.
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>drm.holiday_date.date</code>.
	 */
	public void setDate(org.joda.time.DateTime value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>drm.holiday_date.date</code>.
	 */
	public org.joda.time.DateTime getDate() {
		return (org.joda.time.DateTime) getValue(2);
	}

	/**
	 * Setter for <code>drm.holiday_date.domain_id</code>.
	 */
	public void setDomainId(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>drm.holiday_date.domain_id</code>.
	 */
	public java.lang.String getDomainId() {
		return (java.lang.String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.math.BigInteger> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.math.BigInteger, java.lang.String, org.joda.time.DateTime, java.lang.String> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.math.BigInteger, java.lang.String, org.joda.time.DateTime, java.lang.String> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigInteger> field1() {
		return com.sonicle.webtop.drm.jooq.tables.HolidayDate.HOLIDAY_DATE.HOLIDAY_DATE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.sonicle.webtop.drm.jooq.tables.HolidayDate.HOLIDAY_DATE.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field3() {
		return com.sonicle.webtop.drm.jooq.tables.HolidayDate.HOLIDAY_DATE.DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.sonicle.webtop.drm.jooq.tables.HolidayDate.HOLIDAY_DATE.DOMAIN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigInteger value1() {
		return getHolidayDateId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value3() {
		return getDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getDomainId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HolidayDateRecord value1(java.math.BigInteger value) {
		setHolidayDateId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HolidayDateRecord value2(java.lang.String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HolidayDateRecord value3(org.joda.time.DateTime value) {
		setDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HolidayDateRecord value4(java.lang.String value) {
		setDomainId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HolidayDateRecord values(java.math.BigInteger value1, java.lang.String value2, org.joda.time.DateTime value3, java.lang.String value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached HolidayDateRecord
	 */
	public HolidayDateRecord() {
		super(com.sonicle.webtop.drm.jooq.tables.HolidayDate.HOLIDAY_DATE);
	}

	/**
	 * Create a detached, initialised HolidayDateRecord
	 */
	public HolidayDateRecord(java.math.BigInteger holidayDateId, java.lang.String description, org.joda.time.DateTime date, java.lang.String domainId) {
		super(com.sonicle.webtop.drm.jooq.tables.HolidayDate.HOLIDAY_DATE);

		setValue(0, holidayDateId);
		setValue(1, description);
		setValue(2, date);
		setValue(3, domainId);
	}
}
