/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TimetableMovementsRecord extends org.jooq.impl.UpdatableRecordImpl<com.sonicle.webtop.drm.jooq.tables.records.TimetableMovementsRecord> implements org.jooq.Record12<java.lang.Integer, java.lang.String, java.lang.String, org.joda.time.DateTime, org.joda.time.DateTime, java.sql.Time, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 1014402992;

	/**
	 * Setter for <code>drm.timetable_movements.movement_id</code>.
	 */
	public void setMovementId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>drm.timetable_movements.movement_id</code>.
	 */
	public java.lang.Integer getMovementId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>drm.timetable_movements.type_movement</code>.
	 */
	public void setTypeMovement(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>drm.timetable_movements.type_movement</code>.
	 */
	public java.lang.String getTypeMovement() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>drm.timetable_movements.operator_id</code>.
	 */
	public void setOperatorId(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>drm.timetable_movements.operator_id</code>.
	 */
	public java.lang.String getOperatorId() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>drm.timetable_movements.date_from</code>.
	 */
	public void setDateFrom(org.joda.time.DateTime value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>drm.timetable_movements.date_from</code>.
	 */
	public org.joda.time.DateTime getDateFrom() {
		return (org.joda.time.DateTime) getValue(3);
	}

	/**
	 * Setter for <code>drm.timetable_movements.date_to</code>.
	 */
	public void setDateTo(org.joda.time.DateTime value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>drm.timetable_movements.date_to</code>.
	 */
	public org.joda.time.DateTime getDateTo() {
		return (org.joda.time.DateTime) getValue(4);
	}

	/**
	 * Setter for <code>drm.timetable_movements.duration</code>.
	 */
	public void setDuration(java.sql.Time value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>drm.timetable_movements.duration</code>.
	 */
	public java.sql.Time getDuration() {
		return (java.sql.Time) getValue(5);
	}

	/**
	 * Setter for <code>drm.timetable_movements.description</code>.
	 */
	public void setDescription(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>drm.timetable_movements.description</code>.
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>drm.timetable_movements.reference</code>.
	 */
	public void setReference(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>drm.timetable_movements.reference</code>.
	 */
	public java.lang.String getReference() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>drm.timetable_movements.state</code>.
	 */
	public void setState(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>drm.timetable_movements.state</code>.
	 */
	public java.lang.String getState() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>drm.timetable_movements.category</code>.
	 */
	public void setCategory(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>drm.timetable_movements.category</code>.
	 */
	public java.lang.String getCategory() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>drm.timetable_movements.n_report</code>.
	 */
	public void setNReport(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>drm.timetable_movements.n_report</code>.
	 */
	public java.lang.String getNReport() {
		return (java.lang.String) getValue(10);
	}

	/**
	 * Setter for <code>drm.timetable_movements.username</code>.
	 */
	public void setUsername(java.lang.String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>drm.timetable_movements.username</code>.
	 */
	public java.lang.String getUsername() {
		return (java.lang.String) getValue(11);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record12 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row12<java.lang.Integer, java.lang.String, java.lang.String, org.joda.time.DateTime, org.joda.time.DateTime, java.sql.Time, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row12) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row12<java.lang.Integer, java.lang.String, java.lang.String, org.joda.time.DateTime, org.joda.time.DateTime, java.sql.Time, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row12) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.sonicle.webtop.drm.jooq.tables.TimetableMovements.TIMETABLE_MOVEMENTS.MOVEMENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.sonicle.webtop.drm.jooq.tables.TimetableMovements.TIMETABLE_MOVEMENTS.TYPE_MOVEMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.sonicle.webtop.drm.jooq.tables.TimetableMovements.TIMETABLE_MOVEMENTS.OPERATOR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field4() {
		return com.sonicle.webtop.drm.jooq.tables.TimetableMovements.TIMETABLE_MOVEMENTS.DATE_FROM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field5() {
		return com.sonicle.webtop.drm.jooq.tables.TimetableMovements.TIMETABLE_MOVEMENTS.DATE_TO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Time> field6() {
		return com.sonicle.webtop.drm.jooq.tables.TimetableMovements.TIMETABLE_MOVEMENTS.DURATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.sonicle.webtop.drm.jooq.tables.TimetableMovements.TIMETABLE_MOVEMENTS.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.sonicle.webtop.drm.jooq.tables.TimetableMovements.TIMETABLE_MOVEMENTS.REFERENCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return com.sonicle.webtop.drm.jooq.tables.TimetableMovements.TIMETABLE_MOVEMENTS.STATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return com.sonicle.webtop.drm.jooq.tables.TimetableMovements.TIMETABLE_MOVEMENTS.CATEGORY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field11() {
		return com.sonicle.webtop.drm.jooq.tables.TimetableMovements.TIMETABLE_MOVEMENTS.N_REPORT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field12() {
		return com.sonicle.webtop.drm.jooq.tables.TimetableMovements.TIMETABLE_MOVEMENTS.USERNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getMovementId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getTypeMovement();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getOperatorId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value4() {
		return getDateFrom();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value5() {
		return getDateTo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Time value6() {
		return getDuration();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getReference();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getState();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getCategory();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value11() {
		return getNReport();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value12() {
		return getUsername();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimetableMovementsRecord value1(java.lang.Integer value) {
		setMovementId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimetableMovementsRecord value2(java.lang.String value) {
		setTypeMovement(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimetableMovementsRecord value3(java.lang.String value) {
		setOperatorId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimetableMovementsRecord value4(org.joda.time.DateTime value) {
		setDateFrom(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimetableMovementsRecord value5(org.joda.time.DateTime value) {
		setDateTo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimetableMovementsRecord value6(java.sql.Time value) {
		setDuration(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimetableMovementsRecord value7(java.lang.String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimetableMovementsRecord value8(java.lang.String value) {
		setReference(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimetableMovementsRecord value9(java.lang.String value) {
		setState(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimetableMovementsRecord value10(java.lang.String value) {
		setCategory(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimetableMovementsRecord value11(java.lang.String value) {
		setNReport(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimetableMovementsRecord value12(java.lang.String value) {
		setUsername(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimetableMovementsRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, org.joda.time.DateTime value4, org.joda.time.DateTime value5, java.sql.Time value6, java.lang.String value7, java.lang.String value8, java.lang.String value9, java.lang.String value10, java.lang.String value11, java.lang.String value12) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TimetableMovementsRecord
	 */
	public TimetableMovementsRecord() {
		super(com.sonicle.webtop.drm.jooq.tables.TimetableMovements.TIMETABLE_MOVEMENTS);
	}

	/**
	 * Create a detached, initialised TimetableMovementsRecord
	 */
	public TimetableMovementsRecord(java.lang.Integer movementId, java.lang.String typeMovement, java.lang.String operatorId, org.joda.time.DateTime dateFrom, org.joda.time.DateTime dateTo, java.sql.Time duration, java.lang.String description, java.lang.String reference, java.lang.String state, java.lang.String category, java.lang.String nReport, java.lang.String username) {
		super(com.sonicle.webtop.drm.jooq.tables.TimetableMovements.TIMETABLE_MOVEMENTS);

		setValue(0, movementId);
		setValue(1, typeMovement);
		setValue(2, operatorId);
		setValue(3, dateFrom);
		setValue(4, dateTo);
		setValue(5, duration);
		setValue(6, description);
		setValue(7, reference);
		setValue(8, state);
		setValue(9, category);
		setValue(10, nReport);
		setValue(11, username);
	}
}
