/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TimetableRequestsHolidayRecord extends org.jooq.impl.UpdatableRecordImpl<com.sonicle.webtop.drm.jooq.tables.records.TimetableRequestsHolidayRecord> implements org.jooq.Record16<java.math.BigInteger, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, org.joda.time.DateTime, org.joda.time.DateTime, java.lang.String, java.lang.String, java.lang.String, java.lang.String, org.joda.time.DateTime, java.lang.String, java.math.BigInteger, java.lang.String> {

	private static final long serialVersionUID = -1359795696;

	/**
	 * Setter for <code>drm.timetable_requests_holiday.holiday_id</code>.
	 */
	public void setHolidayId(java.math.BigInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>drm.timetable_requests_holiday.holiday_id</code>.
	 */
	public java.math.BigInteger getHolidayId() {
		return (java.math.BigInteger) getValue(0);
	}

	/**
	 * Setter for <code>drm.timetable_requests_holiday.login</code>.
	 */
	public void setLogin(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>drm.timetable_requests_holiday.login</code>.
	 */
	public java.lang.String getLogin() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>drm.timetable_requests_holiday.domain_id</code>.
	 */
	public void setDomainId(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>drm.timetable_requests_holiday.domain_id</code>.
	 */
	public java.lang.String getDomainId() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>drm.timetable_requests_holiday.type</code>.
	 */
	public void setType(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>drm.timetable_requests_holiday.type</code>.
	 */
	public java.lang.String getType() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>drm.timetable_requests_holiday.responsible</code>.
	 */
	public void setResponsible(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>drm.timetable_requests_holiday.responsible</code>.
	 */
	public java.lang.String getResponsible() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>drm.timetable_requests_holiday.email_responsible</code>.
	 */
	public void setEmailResponsible(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>drm.timetable_requests_holiday.email_responsible</code>.
	 */
	public java.lang.String getEmailResponsible() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>drm.timetable_requests_holiday.date_from</code>.
	 */
	public void setDateFrom(org.joda.time.DateTime value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>drm.timetable_requests_holiday.date_from</code>.
	 */
	public org.joda.time.DateTime getDateFrom() {
		return (org.joda.time.DateTime) getValue(6);
	}

	/**
	 * Setter for <code>drm.timetable_requests_holiday.date_to</code>.
	 */
	public void setDateTo(org.joda.time.DateTime value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>drm.timetable_requests_holiday.date_to</code>.
	 */
	public org.joda.time.DateTime getDateTo() {
		return (org.joda.time.DateTime) getValue(7);
	}

	/**
	 * Setter for <code>drm.timetable_requests_holiday.h_from</code>.
	 */
	public void setHFrom(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>drm.timetable_requests_holiday.h_from</code>.
	 */
	public java.lang.String getHFrom() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>drm.timetable_requests_holiday.h_to</code>.
	 */
	public void setHTo(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>drm.timetable_requests_holiday.h_to</code>.
	 */
	public java.lang.String getHTo() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>drm.timetable_requests_holiday.status</code>.
	 */
	public void setStatus(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>drm.timetable_requests_holiday.status</code>.
	 */
	public java.lang.String getStatus() {
		return (java.lang.String) getValue(10);
	}

	/**
	 * Setter for <code>drm.timetable_requests_holiday.approved</code>.
	 */
	public void setApproved(java.lang.String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>drm.timetable_requests_holiday.approved</code>.
	 */
	public java.lang.String getApproved() {
		return (java.lang.String) getValue(11);
	}

	/**
	 * Setter for <code>drm.timetable_requests_holiday.date_request</code>.
	 */
	public void setDateRequest(org.joda.time.DateTime value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>drm.timetable_requests_holiday.date_request</code>.
	 */
	public org.joda.time.DateTime getDateRequest() {
		return (org.joda.time.DateTime) getValue(12);
	}

	/**
	 * Setter for <code>drm.timetable_requests_holiday.request_cancel</code>.
	 */
	public void setRequestCancel(java.lang.String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>drm.timetable_requests_holiday.request_cancel</code>.
	 */
	public java.lang.String getRequestCancel() {
		return (java.lang.String) getValue(13);
	}

	/**
	 * Setter for <code>drm.timetable_requests_holiday.event_id</code>.
	 */
	public void setEventId(java.math.BigInteger value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>drm.timetable_requests_holiday.event_id</code>.
	 */
	public java.math.BigInteger getEventId() {
		return (java.math.BigInteger) getValue(14);
	}

	/**
	 * Setter for <code>drm.timetable_requests_holiday.note</code>.
	 */
	public void setNote(java.lang.String value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>drm.timetable_requests_holiday.note</code>.
	 */
	public java.lang.String getNote() {
		return (java.lang.String) getValue(15);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.math.BigInteger> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record16 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row16<java.math.BigInteger, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, org.joda.time.DateTime, org.joda.time.DateTime, java.lang.String, java.lang.String, java.lang.String, java.lang.String, org.joda.time.DateTime, java.lang.String, java.math.BigInteger, java.lang.String> fieldsRow() {
		return (org.jooq.Row16) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row16<java.math.BigInteger, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, org.joda.time.DateTime, org.joda.time.DateTime, java.lang.String, java.lang.String, java.lang.String, java.lang.String, org.joda.time.DateTime, java.lang.String, java.math.BigInteger, java.lang.String> valuesRow() {
		return (org.jooq.Row16) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigInteger> field1() {
		return com.sonicle.webtop.drm.jooq.tables.TimetableRequestsHoliday.TIMETABLE_REQUESTS_HOLIDAY.HOLIDAY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.sonicle.webtop.drm.jooq.tables.TimetableRequestsHoliday.TIMETABLE_REQUESTS_HOLIDAY.LOGIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.sonicle.webtop.drm.jooq.tables.TimetableRequestsHoliday.TIMETABLE_REQUESTS_HOLIDAY.DOMAIN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.sonicle.webtop.drm.jooq.tables.TimetableRequestsHoliday.TIMETABLE_REQUESTS_HOLIDAY.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.sonicle.webtop.drm.jooq.tables.TimetableRequestsHoliday.TIMETABLE_REQUESTS_HOLIDAY.RESPONSIBLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.sonicle.webtop.drm.jooq.tables.TimetableRequestsHoliday.TIMETABLE_REQUESTS_HOLIDAY.EMAIL_RESPONSIBLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field7() {
		return com.sonicle.webtop.drm.jooq.tables.TimetableRequestsHoliday.TIMETABLE_REQUESTS_HOLIDAY.DATE_FROM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field8() {
		return com.sonicle.webtop.drm.jooq.tables.TimetableRequestsHoliday.TIMETABLE_REQUESTS_HOLIDAY.DATE_TO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return com.sonicle.webtop.drm.jooq.tables.TimetableRequestsHoliday.TIMETABLE_REQUESTS_HOLIDAY.H_FROM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return com.sonicle.webtop.drm.jooq.tables.TimetableRequestsHoliday.TIMETABLE_REQUESTS_HOLIDAY.H_TO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field11() {
		return com.sonicle.webtop.drm.jooq.tables.TimetableRequestsHoliday.TIMETABLE_REQUESTS_HOLIDAY.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field12() {
		return com.sonicle.webtop.drm.jooq.tables.TimetableRequestsHoliday.TIMETABLE_REQUESTS_HOLIDAY.APPROVED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field13() {
		return com.sonicle.webtop.drm.jooq.tables.TimetableRequestsHoliday.TIMETABLE_REQUESTS_HOLIDAY.DATE_REQUEST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field14() {
		return com.sonicle.webtop.drm.jooq.tables.TimetableRequestsHoliday.TIMETABLE_REQUESTS_HOLIDAY.REQUEST_CANCEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigInteger> field15() {
		return com.sonicle.webtop.drm.jooq.tables.TimetableRequestsHoliday.TIMETABLE_REQUESTS_HOLIDAY.EVENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field16() {
		return com.sonicle.webtop.drm.jooq.tables.TimetableRequestsHoliday.TIMETABLE_REQUESTS_HOLIDAY.NOTE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigInteger value1() {
		return getHolidayId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getLogin();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getDomainId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getResponsible();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getEmailResponsible();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value7() {
		return getDateFrom();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value8() {
		return getDateTo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getHFrom();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getHTo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value11() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value12() {
		return getApproved();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value13() {
		return getDateRequest();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value14() {
		return getRequestCancel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigInteger value15() {
		return getEventId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value16() {
		return getNote();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimetableRequestsHolidayRecord value1(java.math.BigInteger value) {
		setHolidayId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimetableRequestsHolidayRecord value2(java.lang.String value) {
		setLogin(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimetableRequestsHolidayRecord value3(java.lang.String value) {
		setDomainId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimetableRequestsHolidayRecord value4(java.lang.String value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimetableRequestsHolidayRecord value5(java.lang.String value) {
		setResponsible(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimetableRequestsHolidayRecord value6(java.lang.String value) {
		setEmailResponsible(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimetableRequestsHolidayRecord value7(org.joda.time.DateTime value) {
		setDateFrom(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimetableRequestsHolidayRecord value8(org.joda.time.DateTime value) {
		setDateTo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimetableRequestsHolidayRecord value9(java.lang.String value) {
		setHFrom(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimetableRequestsHolidayRecord value10(java.lang.String value) {
		setHTo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimetableRequestsHolidayRecord value11(java.lang.String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimetableRequestsHolidayRecord value12(java.lang.String value) {
		setApproved(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimetableRequestsHolidayRecord value13(org.joda.time.DateTime value) {
		setDateRequest(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimetableRequestsHolidayRecord value14(java.lang.String value) {
		setRequestCancel(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimetableRequestsHolidayRecord value15(java.math.BigInteger value) {
		setEventId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimetableRequestsHolidayRecord value16(java.lang.String value) {
		setNote(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimetableRequestsHolidayRecord values(java.math.BigInteger value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, org.joda.time.DateTime value7, org.joda.time.DateTime value8, java.lang.String value9, java.lang.String value10, java.lang.String value11, java.lang.String value12, org.joda.time.DateTime value13, java.lang.String value14, java.math.BigInteger value15, java.lang.String value16) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TimetableRequestsHolidayRecord
	 */
	public TimetableRequestsHolidayRecord() {
		super(com.sonicle.webtop.drm.jooq.tables.TimetableRequestsHoliday.TIMETABLE_REQUESTS_HOLIDAY);
	}

	/**
	 * Create a detached, initialised TimetableRequestsHolidayRecord
	 */
	public TimetableRequestsHolidayRecord(java.math.BigInteger holidayId, java.lang.String login, java.lang.String domainId, java.lang.String type, java.lang.String responsible, java.lang.String emailResponsible, org.joda.time.DateTime dateFrom, org.joda.time.DateTime dateTo, java.lang.String hFrom, java.lang.String hTo, java.lang.String status, java.lang.String approved, org.joda.time.DateTime dateRequest, java.lang.String requestCancel, java.math.BigInteger eventId, java.lang.String note) {
		super(com.sonicle.webtop.drm.jooq.tables.TimetableRequestsHoliday.TIMETABLE_REQUESTS_HOLIDAY);

		setValue(0, holidayId);
		setValue(1, login);
		setValue(2, domainId);
		setValue(3, type);
		setValue(4, responsible);
		setValue(5, emailResponsible);
		setValue(6, dateFrom);
		setValue(7, dateTo);
		setValue(8, hFrom);
		setValue(9, hTo);
		setValue(10, status);
		setValue(11, approved);
		setValue(12, dateRequest);
		setValue(13, requestCancel);
		setValue(14, eventId);
		setValue(15, note);
	}
}
