/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CompaniesUsers extends org.jooq.impl.TableImpl<com.sonicle.webtop.drm.jooq.tables.records.CompaniesUsersRecord> {

	private static final long serialVersionUID = -2079366955;

	/**
	 * The reference instance of <code>drm.companies_users</code>
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.CompaniesUsers COMPANIES_USERS = new com.sonicle.webtop.drm.jooq.tables.CompaniesUsers();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.drm.jooq.tables.records.CompaniesUsersRecord> getRecordType() {
		return com.sonicle.webtop.drm.jooq.tables.records.CompaniesUsersRecord.class;
	}

	/**
	 * The column <code>drm.companies_users.association_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.CompaniesUsersRecord, java.lang.Integer> ASSOCIATION_ID = createField("association_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>drm.companies_users.company_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.CompaniesUsersRecord, java.lang.Integer> COMPANY_ID = createField("company_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>drm.companies_users.user_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.CompaniesUsersRecord, java.lang.String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * Create a <code>drm.companies_users</code> table reference
	 */
	public CompaniesUsers() {
		this("companies_users", null);
	}

	/**
	 * Create an aliased <code>drm.companies_users</code> table reference
	 */
	public CompaniesUsers(java.lang.String alias) {
		this(alias, com.sonicle.webtop.drm.jooq.tables.CompaniesUsers.COMPANIES_USERS);
	}

	private CompaniesUsers(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.drm.jooq.tables.records.CompaniesUsersRecord> aliased) {
		this(alias, aliased, null);
	}

	private CompaniesUsers(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.drm.jooq.tables.records.CompaniesUsersRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.drm.jooq.Drm.DRM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.sonicle.webtop.drm.jooq.tables.records.CompaniesUsersRecord, java.lang.Integer> getIdentity() {
		return com.sonicle.webtop.drm.jooq.Keys.IDENTITY_COMPANIES_USERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.CompaniesUsersRecord> getPrimaryKey() {
		return com.sonicle.webtop.drm.jooq.Keys.COMPANIES_USERS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.CompaniesUsersRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.CompaniesUsersRecord>>asList(com.sonicle.webtop.drm.jooq.Keys.COMPANIES_USERS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.drm.jooq.tables.CompaniesUsers as(java.lang.String alias) {
		return new com.sonicle.webtop.drm.jooq.tables.CompaniesUsers(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.drm.jooq.tables.CompaniesUsers rename(java.lang.String name) {
		return new com.sonicle.webtop.drm.jooq.tables.CompaniesUsers(name, null);
	}
}
