/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DocStatusesGroups extends org.jooq.impl.TableImpl<com.sonicle.webtop.drm.jooq.tables.records.DocStatusesGroupsRecord> {

	private static final long serialVersionUID = -1687763701;

	/**
	 * The reference instance of <code>drm.doc_statuses_groups</code>
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.DocStatusesGroups DOC_STATUSES_GROUPS = new com.sonicle.webtop.drm.jooq.tables.DocStatusesGroups();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.drm.jooq.tables.records.DocStatusesGroupsRecord> getRecordType() {
		return com.sonicle.webtop.drm.jooq.tables.records.DocStatusesGroupsRecord.class;
	}

	/**
	 * The column <code>drm.doc_statuses_groups.association_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.DocStatusesGroupsRecord, java.lang.Integer> ASSOCIATION_ID = createField("association_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>drm.doc_statuses_groups.doc_status_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.DocStatusesGroupsRecord, java.lang.Integer> DOC_STATUS_ID = createField("doc_status_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>drm.doc_statuses_groups.group_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.DocStatusesGroupsRecord, java.lang.String> GROUP_ID = createField("group_id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * Create a <code>drm.doc_statuses_groups</code> table reference
	 */
	public DocStatusesGroups() {
		this("doc_statuses_groups", null);
	}

	/**
	 * Create an aliased <code>drm.doc_statuses_groups</code> table reference
	 */
	public DocStatusesGroups(java.lang.String alias) {
		this(alias, com.sonicle.webtop.drm.jooq.tables.DocStatusesGroups.DOC_STATUSES_GROUPS);
	}

	private DocStatusesGroups(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.drm.jooq.tables.records.DocStatusesGroupsRecord> aliased) {
		this(alias, aliased, null);
	}

	private DocStatusesGroups(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.drm.jooq.tables.records.DocStatusesGroupsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.drm.jooq.Drm.DRM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.sonicle.webtop.drm.jooq.tables.records.DocStatusesGroupsRecord, java.lang.Integer> getIdentity() {
		return com.sonicle.webtop.drm.jooq.Keys.IDENTITY_DOC_STATUSES_GROUPS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.DocStatusesGroupsRecord> getPrimaryKey() {
		return com.sonicle.webtop.drm.jooq.Keys.DOC_STATUSES_GROUPS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.DocStatusesGroupsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.DocStatusesGroupsRecord>>asList(com.sonicle.webtop.drm.jooq.Keys.DOC_STATUSES_GROUPS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.drm.jooq.tables.DocStatusesGroups as(java.lang.String alias) {
		return new com.sonicle.webtop.drm.jooq.tables.DocStatusesGroups(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.drm.jooq.tables.DocStatusesGroups rename(java.lang.String name) {
		return new com.sonicle.webtop.drm.jooq.tables.DocStatusesGroups(name, null);
	}
}
