/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DocStatuses extends org.jooq.impl.TableImpl<com.sonicle.webtop.drm.jooq.tables.records.DocStatusesRecord> {

	private static final long serialVersionUID = -757601842;

	/**
	 * The reference instance of <code>drm.doc_statuses</code>
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.DocStatuses DOC_STATUSES = new com.sonicle.webtop.drm.jooq.tables.DocStatuses();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.drm.jooq.tables.records.DocStatusesRecord> getRecordType() {
		return com.sonicle.webtop.drm.jooq.tables.records.DocStatusesRecord.class;
	}

	/**
	 * The column <code>drm.doc_statuses.doc_status_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.DocStatusesRecord, java.lang.Integer> DOC_STATUS_ID = createField("doc_status_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>drm.doc_statuses.name</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.DocStatusesRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>drm.doc_statuses.description</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.DocStatusesRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>drm.doc_statuses.type</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.DocStatusesRecord, java.lang.String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(1).nullable(false), this, "");

	/**
	 * The column <code>drm.doc_statuses.built_in</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.DocStatusesRecord, java.lang.Boolean> BUILT_IN = createField("built_in", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>drm.doc_statuses</code> table reference
	 */
	public DocStatuses() {
		this("doc_statuses", null);
	}

	/**
	 * Create an aliased <code>drm.doc_statuses</code> table reference
	 */
	public DocStatuses(java.lang.String alias) {
		this(alias, com.sonicle.webtop.drm.jooq.tables.DocStatuses.DOC_STATUSES);
	}

	private DocStatuses(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.drm.jooq.tables.records.DocStatusesRecord> aliased) {
		this(alias, aliased, null);
	}

	private DocStatuses(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.drm.jooq.tables.records.DocStatusesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.drm.jooq.Drm.DRM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.sonicle.webtop.drm.jooq.tables.records.DocStatusesRecord, java.lang.Integer> getIdentity() {
		return com.sonicle.webtop.drm.jooq.Keys.IDENTITY_DOC_STATUSES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.DocStatusesRecord> getPrimaryKey() {
		return com.sonicle.webtop.drm.jooq.Keys.DOC_STATUSES_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.DocStatusesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.DocStatusesRecord>>asList(com.sonicle.webtop.drm.jooq.Keys.DOC_STATUSES_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.drm.jooq.tables.DocStatuses as(java.lang.String alias) {
		return new com.sonicle.webtop.drm.jooq.tables.DocStatuses(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.drm.jooq.tables.DocStatuses rename(java.lang.String name) {
		return new com.sonicle.webtop.drm.jooq.tables.DocStatuses(name, null);
	}
}
