/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExpenseNoteDocuments extends org.jooq.impl.TableImpl<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteDocumentsRecord> {

	private static final long serialVersionUID = 1902866237;

	/**
	 * The reference instance of <code>drm.expense_note_documents</code>
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.ExpenseNoteDocuments EXPENSE_NOTE_DOCUMENTS = new com.sonicle.webtop.drm.jooq.tables.ExpenseNoteDocuments();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteDocumentsRecord> getRecordType() {
		return com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteDocumentsRecord.class;
	}

	/**
	 * The column <code>drm.expense_note_documents.expense_note_document_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteDocumentsRecord, java.math.BigInteger> EXPENSE_NOTE_DOCUMENT_ID = createField("expense_note_document_id", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38).nullable(false), this, "");

	/**
	 * The column <code>drm.expense_note_documents.file</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteDocumentsRecord, java.lang.Long> FILE = createField("file", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>drm.expense_note_documents.filename</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteDocumentsRecord, java.lang.String> FILENAME = createField("filename", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * The column <code>drm.expense_note_documents.expense_note_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteDocumentsRecord, java.math.BigInteger> EXPENSE_NOTE_ID = createField("expense_note_id", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38), this, "");

	/**
	 * The column <code>drm.expense_note_documents.revision</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteDocumentsRecord, org.joda.time.DateTime> REVISION = createField("revision", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "", new com.sonicle.webtop.core.jooq.DateTimeConverter());

	/**
	 * The column <code>drm.expense_note_documents.operator_id_lock_file</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteDocumentsRecord, java.lang.String> OPERATOR_ID_LOCK_FILE = createField("operator_id_lock_file", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * Create a <code>drm.expense_note_documents</code> table reference
	 */
	public ExpenseNoteDocuments() {
		this("expense_note_documents", null);
	}

	/**
	 * Create an aliased <code>drm.expense_note_documents</code> table reference
	 */
	public ExpenseNoteDocuments(java.lang.String alias) {
		this(alias, com.sonicle.webtop.drm.jooq.tables.ExpenseNoteDocuments.EXPENSE_NOTE_DOCUMENTS);
	}

	private ExpenseNoteDocuments(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteDocumentsRecord> aliased) {
		this(alias, aliased, null);
	}

	private ExpenseNoteDocuments(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteDocumentsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.drm.jooq.Drm.DRM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteDocumentsRecord> getPrimaryKey() {
		return com.sonicle.webtop.drm.jooq.Keys.EXPENSE_NOTE_DOCUMENTS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteDocumentsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteDocumentsRecord>>asList(com.sonicle.webtop.drm.jooq.Keys.EXPENSE_NOTE_DOCUMENTS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.drm.jooq.tables.ExpenseNoteDocuments as(java.lang.String alias) {
		return new com.sonicle.webtop.drm.jooq.tables.ExpenseNoteDocuments(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.drm.jooq.tables.ExpenseNoteDocuments rename(java.lang.String name) {
		return new com.sonicle.webtop.drm.jooq.tables.ExpenseNoteDocuments(name, null);
	}
}
