/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExpenseNoteCostTypes extends org.jooq.impl.TableImpl<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteCostTypesRecord> {

	private static final long serialVersionUID = -590838664;

	/**
	 * The reference instance of <code>drm.expense_note_cost_types</code>
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.ExpenseNoteCostTypes EXPENSE_NOTE_COST_TYPES = new com.sonicle.webtop.drm.jooq.tables.ExpenseNoteCostTypes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteCostTypesRecord> getRecordType() {
		return com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteCostTypesRecord.class;
	}

	/**
	 * The column <code>drm.expense_note_cost_types.cost_type_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteCostTypesRecord, java.math.BigInteger> COST_TYPE_ID = createField("cost_type_id", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38).nullable(false), this, "");

	/**
	 * The column <code>drm.expense_note_cost_types.description</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteCostTypesRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>drm.expense_note_cost_types.domain_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteCostTypesRecord, java.lang.String> DOMAIN_ID = createField("domain_id", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * Create a <code>drm.expense_note_cost_types</code> table reference
	 */
	public ExpenseNoteCostTypes() {
		this("expense_note_cost_types", null);
	}

	/**
	 * Create an aliased <code>drm.expense_note_cost_types</code> table reference
	 */
	public ExpenseNoteCostTypes(java.lang.String alias) {
		this(alias, com.sonicle.webtop.drm.jooq.tables.ExpenseNoteCostTypes.EXPENSE_NOTE_COST_TYPES);
	}

	private ExpenseNoteCostTypes(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteCostTypesRecord> aliased) {
		this(alias, aliased, null);
	}

	private ExpenseNoteCostTypes(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteCostTypesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.drm.jooq.Drm.DRM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteCostTypesRecord> getPrimaryKey() {
		return com.sonicle.webtop.drm.jooq.Keys.EXPENSE_NOTE_COST_TYPES_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteCostTypesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteCostTypesRecord>>asList(com.sonicle.webtop.drm.jooq.Keys.EXPENSE_NOTE_COST_TYPES_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.drm.jooq.tables.ExpenseNoteCostTypes as(java.lang.String alias) {
		return new com.sonicle.webtop.drm.jooq.tables.ExpenseNoteCostTypes(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.drm.jooq.tables.ExpenseNoteCostTypes rename(java.lang.String name) {
		return new com.sonicle.webtop.drm.jooq.tables.ExpenseNoteCostTypes(name, null);
	}
}
