/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExpenseNoteRows extends org.jooq.impl.TableImpl<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteRowsRecord> {

	private static final long serialVersionUID = -1125421392;

	/**
	 * The reference instance of <code>drm.expense_note_rows</code>
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.ExpenseNoteRows EXPENSE_NOTE_ROWS = new com.sonicle.webtop.drm.jooq.tables.ExpenseNoteRows();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteRowsRecord> getRecordType() {
		return com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteRowsRecord.class;
	}

	/**
	 * The column <code>drm.expense_note_rows.expense_note_row_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteRowsRecord, java.math.BigInteger> EXPENSE_NOTE_ROW_ID = createField("expense_note_row_id", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38).nullable(false), this, "");

	/**
	 * The column <code>drm.expense_note_rows.expense_note_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteRowsRecord, java.math.BigInteger> EXPENSE_NOTE_ID = createField("expense_note_id", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38), this, "");

	/**
	 * The column <code>drm.expense_note_rows.revision</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteRowsRecord, org.joda.time.DateTime> REVISION = createField("revision", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new com.sonicle.webtop.core.jooq.DateTimeConverter());

	/**
	 * The column <code>drm.expense_note_rows.description</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteRowsRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(150), this, "");

	/**
	 * The column <code>drm.expense_note_rows.km</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteRowsRecord, java.math.BigDecimal> KM = createField("km", org.jooq.impl.SQLDataType.NUMERIC, this, "");

	/**
	 * The column <code>drm.expense_note_rows.stay</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteRowsRecord, java.math.BigDecimal> STAY = createField("stay", org.jooq.impl.SQLDataType.NUMERIC, this, "");

	/**
	 * The column <code>drm.expense_note_rows.highway</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteRowsRecord, java.math.BigDecimal> HIGHWAY = createField("highway", org.jooq.impl.SQLDataType.NUMERIC, this, "");

	/**
	 * The column <code>drm.expense_note_rows.park</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteRowsRecord, java.math.BigDecimal> PARK = createField("park", org.jooq.impl.SQLDataType.NUMERIC, this, "");

	/**
	 * The column <code>drm.expense_note_rows.meals</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteRowsRecord, java.math.BigDecimal> MEALS = createField("meals", org.jooq.impl.SQLDataType.NUMERIC, this, "");

	/**
	 * The column <code>drm.expense_note_rows.amount_km</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteRowsRecord, java.math.BigDecimal> AMOUNT_KM = createField("amount_km", org.jooq.impl.SQLDataType.NUMERIC, this, "");

	/**
	 * The column <code>drm.expense_note_rows.other</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteRowsRecord, java.math.BigDecimal> OTHER = createField("other", org.jooq.impl.SQLDataType.NUMERIC, this, "");

	/**
	 * The column <code>drm.expense_note_rows.total</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteRowsRecord, java.math.BigDecimal> TOTAL = createField("total", org.jooq.impl.SQLDataType.NUMERIC, this, "");

	/**
	 * The column <code>drm.expense_note_rows.date</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteRowsRecord, org.joda.time.DateTime> DATE = createField("date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new com.sonicle.webtop.core.jooq.DateTimeConverter());

	/**
	 * The column <code>drm.expense_note_rows.operator_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteRowsRecord, java.lang.String> OPERATOR_ID = createField("operator_id", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>drm.expense_note_rows.domain_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteRowsRecord, java.lang.String> DOMAIN_ID = createField("domain_id", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>drm.expense_note_rows.customer_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteRowsRecord, java.lang.String> CUSTOMER_ID = createField("customer_id", org.jooq.impl.SQLDataType.VARCHAR.length(36), this, "");

	/**
	 * The column <code>drm.expense_note_rows.payment_company</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteRowsRecord, java.lang.String> PAYMENT_COMPANY = createField("payment_company", org.jooq.impl.SQLDataType.VARCHAR.length(5), this, "");

	/**
	 * The column <code>drm.expense_note_rows.invoice</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteRowsRecord, java.lang.String> INVOICE = createField("invoice", org.jooq.impl.SQLDataType.VARCHAR.length(5), this, "");

	/**
	 * The column <code>drm.expense_note_rows.invoice_number</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteRowsRecord, java.lang.String> INVOICE_NUMBER = createField("invoice_number", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>drm.expense_note_rows.point_of_sale</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteRowsRecord, java.lang.String> POINT_OF_SALE = createField("point_of_sale", org.jooq.impl.SQLDataType.VARCHAR.length(15), this, "");

	/**
	 * Create a <code>drm.expense_note_rows</code> table reference
	 */
	public ExpenseNoteRows() {
		this("expense_note_rows", null);
	}

	/**
	 * Create an aliased <code>drm.expense_note_rows</code> table reference
	 */
	public ExpenseNoteRows(java.lang.String alias) {
		this(alias, com.sonicle.webtop.drm.jooq.tables.ExpenseNoteRows.EXPENSE_NOTE_ROWS);
	}

	private ExpenseNoteRows(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteRowsRecord> aliased) {
		this(alias, aliased, null);
	}

	private ExpenseNoteRows(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteRowsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.drm.jooq.Drm.DRM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteRowsRecord> getPrimaryKey() {
		return com.sonicle.webtop.drm.jooq.Keys.EXPENSE_NOTE_ROWS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteRowsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.ExpenseNoteRowsRecord>>asList(com.sonicle.webtop.drm.jooq.Keys.EXPENSE_NOTE_ROWS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.drm.jooq.tables.ExpenseNoteRows as(java.lang.String alias) {
		return new com.sonicle.webtop.drm.jooq.tables.ExpenseNoteRows(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.drm.jooq.tables.ExpenseNoteRows rename(java.lang.String name) {
		return new com.sonicle.webtop.drm.jooq.tables.ExpenseNoteRows(name, null);
	}
}
