/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Groups extends org.jooq.impl.TableImpl<com.sonicle.webtop.drm.jooq.tables.records.GroupsRecord> {

	private static final long serialVersionUID = -1622769745;

	/**
	 * The reference instance of <code>drm.groups</code>
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.Groups GROUPS = new com.sonicle.webtop.drm.jooq.tables.Groups();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.drm.jooq.tables.records.GroupsRecord> getRecordType() {
		return com.sonicle.webtop.drm.jooq.tables.records.GroupsRecord.class;
	}

	/**
	 * The column <code>drm.groups.group_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.GroupsRecord, java.lang.String> GROUP_ID = createField("group_id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>drm.groups.domain_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.GroupsRecord, java.lang.String> DOMAIN_ID = createField("domain_id", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>drm.groups.group_category</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.GroupsRecord, java.lang.String> GROUP_CATEGORY = createField("group_category", org.jooq.impl.SQLDataType.VARCHAR.length(1).nullable(false), this, "");

	/**
	 * The column <code>drm.groups.name</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.GroupsRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>drm.groups.description</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.GroupsRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>drm.groups.group_type</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.GroupsRecord, java.lang.String> GROUP_TYPE = createField("group_type", org.jooq.impl.SQLDataType.VARCHAR.length(1).nullable(false), this, "");

	/**
	 * The column <code>drm.groups.customer_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.GroupsRecord, java.lang.String> CUSTOMER_ID = createField("customer_id", org.jooq.impl.SQLDataType.VARCHAR.length(15), this, "");

	/**
	 * The column <code>drm.groups.supervisior_user_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.GroupsRecord, java.lang.String> SUPERVISIOR_USER_ID = createField("supervisior_user_id", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * Create a <code>drm.groups</code> table reference
	 */
	public Groups() {
		this("groups", null);
	}

	/**
	 * Create an aliased <code>drm.groups</code> table reference
	 */
	public Groups(java.lang.String alias) {
		this(alias, com.sonicle.webtop.drm.jooq.tables.Groups.GROUPS);
	}

	private Groups(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.drm.jooq.tables.records.GroupsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Groups(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.drm.jooq.tables.records.GroupsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.drm.jooq.Drm.DRM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.GroupsRecord> getPrimaryKey() {
		return com.sonicle.webtop.drm.jooq.Keys.GROUPS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.GroupsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.GroupsRecord>>asList(com.sonicle.webtop.drm.jooq.Keys.GROUPS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.drm.jooq.tables.Groups as(java.lang.String alias) {
		return new com.sonicle.webtop.drm.jooq.tables.Groups(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.drm.jooq.tables.Groups rename(java.lang.String name) {
		return new com.sonicle.webtop.drm.jooq.tables.Groups(name, null);
	}
}
