/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LeaveRequestDocuments extends org.jooq.impl.TableImpl<com.sonicle.webtop.drm.jooq.tables.records.LeaveRequestDocumentsRecord> {

	private static final long serialVersionUID = -1496141211;

	/**
	 * The reference instance of <code>drm.leave_request_documents</code>
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.LeaveRequestDocuments LEAVE_REQUEST_DOCUMENTS = new com.sonicle.webtop.drm.jooq.tables.LeaveRequestDocuments();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.drm.jooq.tables.records.LeaveRequestDocumentsRecord> getRecordType() {
		return com.sonicle.webtop.drm.jooq.tables.records.LeaveRequestDocumentsRecord.class;
	}

	/**
	 * The column <code>drm.leave_request_documents.leave_request_document_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.LeaveRequestDocumentsRecord, java.lang.String> LEAVE_REQUEST_DOCUMENT_ID = createField("leave_request_document_id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>drm.leave_request_documents.leave_request_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.LeaveRequestDocumentsRecord, java.lang.Integer> LEAVE_REQUEST_ID = createField("leave_request_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>drm.leave_request_documents.revision_timestamp</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.LeaveRequestDocumentsRecord, org.joda.time.DateTime> REVISION_TIMESTAMP = createField("revision_timestamp", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "", new com.sonicle.webtop.core.jooq.DateTimeConverter());

	/**
	 * The column <code>drm.leave_request_documents.revision_sequence</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.LeaveRequestDocumentsRecord, java.lang.Short> REVISION_SEQUENCE = createField("revision_sequence", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * The column <code>drm.leave_request_documents.filename</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.LeaveRequestDocumentsRecord, java.lang.String> FILENAME = createField("filename", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>drm.leave_request_documents.size</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.LeaveRequestDocumentsRecord, java.lang.Integer> SIZE = createField("size", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>drm.leave_request_documents.media_tpye</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.LeaveRequestDocumentsRecord, java.lang.String> MEDIA_TPYE = createField("media_tpye", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * Create a <code>drm.leave_request_documents</code> table reference
	 */
	public LeaveRequestDocuments() {
		this("leave_request_documents", null);
	}

	/**
	 * Create an aliased <code>drm.leave_request_documents</code> table reference
	 */
	public LeaveRequestDocuments(java.lang.String alias) {
		this(alias, com.sonicle.webtop.drm.jooq.tables.LeaveRequestDocuments.LEAVE_REQUEST_DOCUMENTS);
	}

	private LeaveRequestDocuments(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.drm.jooq.tables.records.LeaveRequestDocumentsRecord> aliased) {
		this(alias, aliased, null);
	}

	private LeaveRequestDocuments(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.drm.jooq.tables.records.LeaveRequestDocumentsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.drm.jooq.Drm.DRM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.LeaveRequestDocumentsRecord> getPrimaryKey() {
		return com.sonicle.webtop.drm.jooq.Keys.LEAVE_REQUEST_DOCUMENTS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.LeaveRequestDocumentsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.LeaveRequestDocumentsRecord>>asList(com.sonicle.webtop.drm.jooq.Keys.LEAVE_REQUEST_DOCUMENTS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.drm.jooq.tables.LeaveRequestDocuments as(java.lang.String alias) {
		return new com.sonicle.webtop.drm.jooq.tables.LeaveRequestDocuments(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.drm.jooq.tables.LeaveRequestDocuments rename(java.lang.String name) {
		return new com.sonicle.webtop.drm.jooq.tables.LeaveRequestDocuments(name, null);
	}
}
