/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfilesMasterdata extends org.jooq.impl.TableImpl<com.sonicle.webtop.drm.jooq.tables.records.ProfilesMasterdataRecord> {

	private static final long serialVersionUID = -1117761149;

	/**
	 * The reference instance of <code>drm.profiles_masterdata</code>
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.ProfilesMasterdata PROFILES_MASTERDATA = new com.sonicle.webtop.drm.jooq.tables.ProfilesMasterdata();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.drm.jooq.tables.records.ProfilesMasterdataRecord> getRecordType() {
		return com.sonicle.webtop.drm.jooq.tables.records.ProfilesMasterdataRecord.class;
	}

	/**
	 * The column <code>drm.profiles_masterdata.id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ProfilesMasterdataRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>drm.profiles_masterdata.profile_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ProfilesMasterdataRecord, java.lang.String> PROFILE_ID = createField("profile_id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>drm.profiles_masterdata.master_data_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ProfilesMasterdataRecord, java.lang.String> MASTER_DATA_ID = createField("master_data_id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * Create a <code>drm.profiles_masterdata</code> table reference
	 */
	public ProfilesMasterdata() {
		this("profiles_masterdata", null);
	}

	/**
	 * Create an aliased <code>drm.profiles_masterdata</code> table reference
	 */
	public ProfilesMasterdata(java.lang.String alias) {
		this(alias, com.sonicle.webtop.drm.jooq.tables.ProfilesMasterdata.PROFILES_MASTERDATA);
	}

	private ProfilesMasterdata(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.drm.jooq.tables.records.ProfilesMasterdataRecord> aliased) {
		this(alias, aliased, null);
	}

	private ProfilesMasterdata(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.drm.jooq.tables.records.ProfilesMasterdataRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.drm.jooq.Drm.DRM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.sonicle.webtop.drm.jooq.tables.records.ProfilesMasterdataRecord, java.lang.Integer> getIdentity() {
		return com.sonicle.webtop.drm.jooq.Keys.IDENTITY_PROFILES_MASTERDATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.ProfilesMasterdataRecord> getPrimaryKey() {
		return com.sonicle.webtop.drm.jooq.Keys.PROFILES_MASTERDATA_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.ProfilesMasterdataRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.ProfilesMasterdataRecord>>asList(com.sonicle.webtop.drm.jooq.Keys.PROFILES_MASTERDATA_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.drm.jooq.tables.ProfilesMasterdata as(java.lang.String alias) {
		return new com.sonicle.webtop.drm.jooq.tables.ProfilesMasterdata(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.drm.jooq.tables.ProfilesMasterdata rename(java.lang.String name) {
		return new com.sonicle.webtop.drm.jooq.tables.ProfilesMasterdata(name, null);
	}
}
