/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfilesUsers extends org.jooq.impl.TableImpl<com.sonicle.webtop.drm.jooq.tables.records.ProfilesUsersRecord> {

	private static final long serialVersionUID = 311778417;

	/**
	 * The reference instance of <code>drm.profiles_users</code>
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.ProfilesUsers PROFILES_USERS = new com.sonicle.webtop.drm.jooq.tables.ProfilesUsers();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.drm.jooq.tables.records.ProfilesUsersRecord> getRecordType() {
		return com.sonicle.webtop.drm.jooq.tables.records.ProfilesUsersRecord.class;
	}

	/**
	 * The column <code>drm.profiles_users.id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ProfilesUsersRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>drm.profiles_users.profile_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ProfilesUsersRecord, java.lang.String> PROFILE_ID = createField("profile_id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>drm.profiles_users.user_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.ProfilesUsersRecord, java.lang.String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * Create a <code>drm.profiles_users</code> table reference
	 */
	public ProfilesUsers() {
		this("profiles_users", null);
	}

	/**
	 * Create an aliased <code>drm.profiles_users</code> table reference
	 */
	public ProfilesUsers(java.lang.String alias) {
		this(alias, com.sonicle.webtop.drm.jooq.tables.ProfilesUsers.PROFILES_USERS);
	}

	private ProfilesUsers(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.drm.jooq.tables.records.ProfilesUsersRecord> aliased) {
		this(alias, aliased, null);
	}

	private ProfilesUsers(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.drm.jooq.tables.records.ProfilesUsersRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.drm.jooq.Drm.DRM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.sonicle.webtop.drm.jooq.tables.records.ProfilesUsersRecord, java.lang.Integer> getIdentity() {
		return com.sonicle.webtop.drm.jooq.Keys.IDENTITY_PROFILES_USERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.ProfilesUsersRecord> getPrimaryKey() {
		return com.sonicle.webtop.drm.jooq.Keys.PROFILES_USERS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.ProfilesUsersRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.ProfilesUsersRecord>>asList(com.sonicle.webtop.drm.jooq.Keys.PROFILES_USERS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.drm.jooq.tables.ProfilesUsers as(java.lang.String alias) {
		return new com.sonicle.webtop.drm.jooq.tables.ProfilesUsers(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.drm.jooq.tables.ProfilesUsers rename(java.lang.String name) {
		return new com.sonicle.webtop.drm.jooq.tables.ProfilesUsers(name, null);
	}
}
