/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TimetableMovements extends org.jooq.impl.TableImpl<com.sonicle.webtop.drm.jooq.tables.records.TimetableMovementsRecord> {

	private static final long serialVersionUID = 508766078;

	/**
	 * The reference instance of <code>drm.timetable_movements</code>
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.TimetableMovements TIMETABLE_MOVEMENTS = new com.sonicle.webtop.drm.jooq.tables.TimetableMovements();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.drm.jooq.tables.records.TimetableMovementsRecord> getRecordType() {
		return com.sonicle.webtop.drm.jooq.tables.records.TimetableMovementsRecord.class;
	}

	/**
	 * The column <code>drm.timetable_movements.movement_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.TimetableMovementsRecord, java.lang.Integer> MOVEMENT_ID = createField("movement_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>drm.timetable_movements.type_movement</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.TimetableMovementsRecord, java.lang.String> TYPE_MOVEMENT = createField("type_movement", org.jooq.impl.SQLDataType.VARCHAR.length(2).nullable(false), this, "");

	/**
	 * The column <code>drm.timetable_movements.operator_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.TimetableMovementsRecord, java.lang.String> OPERATOR_ID = createField("operator_id", org.jooq.impl.SQLDataType.VARCHAR.length(15).nullable(false), this, "");

	/**
	 * The column <code>drm.timetable_movements.date_from</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.TimetableMovementsRecord, org.joda.time.DateTime> DATE_FROM = createField("date_from", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "", new com.sonicle.webtop.core.jooq.DateTimeConverter());

	/**
	 * The column <code>drm.timetable_movements.date_to</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.TimetableMovementsRecord, org.joda.time.DateTime> DATE_TO = createField("date_to", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "", new com.sonicle.webtop.core.jooq.DateTimeConverter());

	/**
	 * The column <code>drm.timetable_movements.duration</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.TimetableMovementsRecord, java.sql.Time> DURATION = createField("duration", org.jooq.impl.SQLDataType.TIME.nullable(false), this, "");

	/**
	 * The column <code>drm.timetable_movements.description</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.TimetableMovementsRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * The column <code>drm.timetable_movements.reference</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.TimetableMovementsRecord, java.lang.String> REFERENCE = createField("reference", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>drm.timetable_movements.state</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.TimetableMovementsRecord, java.lang.String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>drm.timetable_movements.category</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.TimetableMovementsRecord, java.lang.String> CATEGORY = createField("category", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>drm.timetable_movements.n_report</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.TimetableMovementsRecord, java.lang.String> N_REPORT = createField("n_report", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>drm.timetable_movements.username</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.TimetableMovementsRecord, java.lang.String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * Create a <code>drm.timetable_movements</code> table reference
	 */
	public TimetableMovements() {
		this("timetable_movements", null);
	}

	/**
	 * Create an aliased <code>drm.timetable_movements</code> table reference
	 */
	public TimetableMovements(java.lang.String alias) {
		this(alias, com.sonicle.webtop.drm.jooq.tables.TimetableMovements.TIMETABLE_MOVEMENTS);
	}

	private TimetableMovements(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.drm.jooq.tables.records.TimetableMovementsRecord> aliased) {
		this(alias, aliased, null);
	}

	private TimetableMovements(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.drm.jooq.tables.records.TimetableMovementsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.drm.jooq.Drm.DRM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.TimetableMovementsRecord> getPrimaryKey() {
		return com.sonicle.webtop.drm.jooq.Keys.TIMETABLE_MOVEMENTS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.TimetableMovementsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.TimetableMovementsRecord>>asList(com.sonicle.webtop.drm.jooq.Keys.TIMETABLE_MOVEMENTS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.drm.jooq.tables.TimetableMovements as(java.lang.String alias) {
		return new com.sonicle.webtop.drm.jooq.tables.TimetableMovements(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.drm.jooq.tables.TimetableMovements rename(java.lang.String name) {
		return new com.sonicle.webtop.drm.jooq.tables.TimetableMovements(name, null);
	}
}
