/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TimetableSettings extends org.jooq.impl.TableImpl<com.sonicle.webtop.drm.jooq.tables.records.TimetableSettingsRecord> {

	private static final long serialVersionUID = 1667467396;

	/**
	 * The reference instance of <code>drm.timetable_settings</code>
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.TimetableSettings TIMETABLE_SETTINGS = new com.sonicle.webtop.drm.jooq.tables.TimetableSettings();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.drm.jooq.tables.records.TimetableSettingsRecord> getRecordType() {
		return com.sonicle.webtop.drm.jooq.tables.records.TimetableSettingsRecord.class;
	}

	/**
	 * The column <code>drm.timetable_settings.timetable_setting_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.TimetableSettingsRecord, java.lang.Integer> TIMETABLE_SETTING_ID = createField("timetable_setting_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>drm.timetable_settings.domain_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.TimetableSettingsRecord, java.lang.String> DOMAIN_ID = createField("domain_id", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>drm.timetable_settings.allowed_addresses</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.TimetableSettingsRecord, java.lang.String> ALLOWED_ADDRESSES = createField("allowed_addresses", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>drm.timetable_settings.allowed_users</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.TimetableSettingsRecord, java.lang.String> ALLOWED_USERS = createField("allowed_users", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>drm.timetable_settings.staff_office_email</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.TimetableSettingsRecord, java.lang.String> STAFF_OFFICE_EMAIL = createField("staff_office_email", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>drm.timetable_settings.requests_holidays_permits_previous_dates</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.TimetableSettingsRecord, java.lang.Boolean> REQUESTS_HOLIDAYS_PERMITS_PREVIOUS_DATES = createField("requests_holidays_permits_previous_dates", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>drm.timetable_settings.total_tolerance_in_minutes</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.TimetableSettingsRecord, java.lang.String> TOTAL_TOLERANCE_IN_MINUTES = createField("total_tolerance_in_minutes", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>drm.timetable_settings.rounding</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.TimetableSettingsRecord, java.lang.String> ROUNDING = createField("rounding", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>drm.timetable_settings.minimum_extraordinary</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.TimetableSettingsRecord, java.lang.String> MINIMUM_EXTRAORDINARY = createField("minimum_extraordinary", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>drm.timetable_settings.break_anomaly</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.TimetableSettingsRecord, java.lang.Boolean> BREAK_ANOMALY = createField("break_anomaly", org.jooq.impl.SQLDataType.BOOLEAN.defaulted(true), this, "");

	/**
	 * The column <code>drm.timetable_settings.read_only_events</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.TimetableSettingsRecord, java.lang.Boolean> READ_ONLY_EVENTS = createField("read_only_events", org.jooq.impl.SQLDataType.BOOLEAN.defaulted(true), this, "");

	/**
	 * The column <code>drm.timetable_settings.requests_permits_not_remunered</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.TimetableSettingsRecord, java.lang.Boolean> REQUESTS_PERMITS_NOT_REMUNERED = createField("requests_permits_not_remunered", org.jooq.impl.SQLDataType.BOOLEAN.defaulted(true), this, "");

	/**
	 * The column <code>drm.timetable_settings.requests_permits_medical_visits</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.TimetableSettingsRecord, java.lang.Boolean> REQUESTS_PERMITS_MEDICAL_VISITS = createField("requests_permits_medical_visits", org.jooq.impl.SQLDataType.BOOLEAN.defaulted(true), this, "");

	/**
	 * The column <code>drm.timetable_settings.requests_permits_contractuals</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.TimetableSettingsRecord, java.lang.Boolean> REQUESTS_PERMITS_CONTRACTUALS = createField("requests_permits_contractuals", org.jooq.impl.SQLDataType.BOOLEAN.defaulted(true), this, "");

	/**
	 * Create a <code>drm.timetable_settings</code> table reference
	 */
	public TimetableSettings() {
		this("timetable_settings", null);
	}

	/**
	 * Create an aliased <code>drm.timetable_settings</code> table reference
	 */
	public TimetableSettings(java.lang.String alias) {
		this(alias, com.sonicle.webtop.drm.jooq.tables.TimetableSettings.TIMETABLE_SETTINGS);
	}

	private TimetableSettings(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.drm.jooq.tables.records.TimetableSettingsRecord> aliased) {
		this(alias, aliased, null);
	}

	private TimetableSettings(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.drm.jooq.tables.records.TimetableSettingsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.drm.jooq.Drm.DRM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.TimetableSettingsRecord> getPrimaryKey() {
		return com.sonicle.webtop.drm.jooq.Keys.TIMETABLE_SETTINGS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.TimetableSettingsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.TimetableSettingsRecord>>asList(com.sonicle.webtop.drm.jooq.Keys.TIMETABLE_SETTINGS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.drm.jooq.tables.TimetableSettings as(java.lang.String alias) {
		return new com.sonicle.webtop.drm.jooq.tables.TimetableSettings(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.drm.jooq.tables.TimetableSettings rename(java.lang.String name) {
		return new com.sonicle.webtop.drm.jooq.tables.TimetableSettings(name, null);
	}
}
