/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkReportsDetails extends org.jooq.impl.TableImpl<com.sonicle.webtop.drm.jooq.tables.records.WorkReportsDetailsRecord> {

	private static final long serialVersionUID = 115797794;

	/**
	 * The reference instance of <code>drm.work_reports_details</code>
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.WorkReportsDetails WORK_REPORTS_DETAILS = new com.sonicle.webtop.drm.jooq.tables.WorkReportsDetails();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.drm.jooq.tables.records.WorkReportsDetailsRecord> getRecordType() {
		return com.sonicle.webtop.drm.jooq.tables.records.WorkReportsDetailsRecord.class;
	}

	/**
	 * The column <code>drm.work_reports_details.id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.WorkReportsDetailsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>drm.work_reports_details.work_report_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.WorkReportsDetailsRecord, java.lang.String> WORK_REPORT_ID = createField("work_report_id", org.jooq.impl.SQLDataType.VARCHAR.length(36), this, "");

	/**
	 * The column <code>drm.work_reports_details.row_no</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.WorkReportsDetailsRecord, java.lang.Short> ROW_NO = createField("row_no", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>drm.work_reports_details.work_type_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.WorkReportsDetailsRecord, java.lang.Integer> WORK_TYPE_ID = createField("work_type_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>drm.work_reports_details.duration</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.WorkReportsDetailsRecord, java.lang.Short> DURATION = createField("duration", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>drm.work_reports_details.row_flag</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.WorkReportsDetailsRecord, java.lang.String> ROW_FLAG = createField("row_flag", org.jooq.impl.SQLDataType.VARCHAR.length(1), this, "");

	/**
	 * Create a <code>drm.work_reports_details</code> table reference
	 */
	public WorkReportsDetails() {
		this("work_reports_details", null);
	}

	/**
	 * Create an aliased <code>drm.work_reports_details</code> table reference
	 */
	public WorkReportsDetails(java.lang.String alias) {
		this(alias, com.sonicle.webtop.drm.jooq.tables.WorkReportsDetails.WORK_REPORTS_DETAILS);
	}

	private WorkReportsDetails(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.drm.jooq.tables.records.WorkReportsDetailsRecord> aliased) {
		this(alias, aliased, null);
	}

	private WorkReportsDetails(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.drm.jooq.tables.records.WorkReportsDetailsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.drm.jooq.Drm.DRM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.sonicle.webtop.drm.jooq.tables.records.WorkReportsDetailsRecord, java.lang.Integer> getIdentity() {
		return com.sonicle.webtop.drm.jooq.Keys.IDENTITY_WORK_REPORTS_DETAILS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.WorkReportsDetailsRecord> getPrimaryKey() {
		return com.sonicle.webtop.drm.jooq.Keys.REPORTS_DETAILS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.WorkReportsDetailsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.WorkReportsDetailsRecord>>asList(com.sonicle.webtop.drm.jooq.Keys.REPORTS_DETAILS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.drm.jooq.tables.WorkReportsDetails as(java.lang.String alias) {
		return new com.sonicle.webtop.drm.jooq.tables.WorkReportsDetails(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.drm.jooq.tables.WorkReportsDetails rename(java.lang.String name) {
		return new com.sonicle.webtop.drm.jooq.tables.WorkReportsDetails(name, null);
	}
}
