/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.drm.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkTypes extends org.jooq.impl.TableImpl<com.sonicle.webtop.drm.jooq.tables.records.WorkTypesRecord> {

	private static final long serialVersionUID = -178275593;

	/**
	 * The reference instance of <code>drm.work_types</code>
	 */
	public static final com.sonicle.webtop.drm.jooq.tables.WorkTypes WORK_TYPES = new com.sonicle.webtop.drm.jooq.tables.WorkTypes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.drm.jooq.tables.records.WorkTypesRecord> getRecordType() {
		return com.sonicle.webtop.drm.jooq.tables.records.WorkTypesRecord.class;
	}

	/**
	 * The column <code>drm.work_types.work_type_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.WorkTypesRecord, java.lang.Integer> WORK_TYPE_ID = createField("work_type_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>drm.work_types.domain_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.WorkTypesRecord, java.lang.String> DOMAIN_ID = createField("domain_id", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>drm.work_types.revision_status</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.WorkTypesRecord, java.lang.String> REVISION_STATUS = createField("revision_status", org.jooq.impl.SQLDataType.VARCHAR.length(1).nullable(false), this, "");

	/**
	 * The column <code>drm.work_types.external_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.WorkTypesRecord, java.lang.String> EXTERNAL_ID = createField("external_id", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>drm.work_types.description</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.drm.jooq.tables.records.WorkTypesRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * Create a <code>drm.work_types</code> table reference
	 */
	public WorkTypes() {
		this("work_types", null);
	}

	/**
	 * Create an aliased <code>drm.work_types</code> table reference
	 */
	public WorkTypes(java.lang.String alias) {
		this(alias, com.sonicle.webtop.drm.jooq.tables.WorkTypes.WORK_TYPES);
	}

	private WorkTypes(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.drm.jooq.tables.records.WorkTypesRecord> aliased) {
		this(alias, aliased, null);
	}

	private WorkTypes(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.drm.jooq.tables.records.WorkTypesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.drm.jooq.Drm.DRM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.sonicle.webtop.drm.jooq.tables.records.WorkTypesRecord, java.lang.Integer> getIdentity() {
		return com.sonicle.webtop.drm.jooq.Keys.IDENTITY_WORK_TYPES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.WorkTypesRecord> getPrimaryKey() {
		return com.sonicle.webtop.drm.jooq.Keys.RATES_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.WorkTypesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.drm.jooq.tables.records.WorkTypesRecord>>asList(com.sonicle.webtop.drm.jooq.Keys.RATES_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.drm.jooq.tables.WorkTypes as(java.lang.String alias) {
		return new com.sonicle.webtop.drm.jooq.tables.WorkTypes(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.drm.jooq.tables.WorkTypes rename(java.lang.String name) {
		return new com.sonicle.webtop.drm.jooq.tables.WorkTypes(name, null);
	}
}
